{"matches":[{"vulnerability":{"id":"CVE-2024-6232","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6232","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/34ddb64d088dd7ccc321f6103d23153256caa5d4","https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06","https://github.com/python/cpython/commit/743acbe872485dc18df4d8ab2dc7895187f062c4","https://github.com/python/cpython/commit/7d1f50cd92ff7e10a1c15a8f591dde8a6843a64d","https://github.com/python/cpython/commit/b4225ca91547aa97ed3aca391614afbb255bc877","https://github.com/python/cpython/commit/d449caf8a179e3b954268b3a88eb9170be3c8fbf","https://github.com/python/cpython/commit/ed3a49ea734ada357ff4442996fd4ae71d253373","https://github.com/python/cpython/issues/121285","https://github.com/python/cpython/pull/121286","https://mail.python.org/archives/list/security-announce@python.org/thread/JRYFTPRHZRTLMZLWQEUHZSJXNHM4ACTY/","http://www.openwall.com/lists/oss-security/2024/09/03/5","https://security.netapp.com/advisory/ntap-20241018-0007/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\n\n\n\n\nRegular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6232","epss":0.00834,"percentile":0.73563,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.6255000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-6232","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-0938","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-0938","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/526617ed68cde460236c973e5d0a8bad4de896ba","https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403","https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568","https://github.com/python/cpython/commit/b8b4b713c5f8ec0958c7ef8d29d6711889bc94ab","https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a","https://github.com/python/cpython/commit/ff4e5c25666f63544071a6b075ae8b25c98b7a32","https://github.com/python/cpython/issues/105704","https://github.com/python/cpython/pull/129418","https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/","https://security.netapp.com/advisory/ntap-20250314-0002/"],"description":"The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-0938","epss":0.01039,"percentile":0.76414,"date":"2025-06-02"}],"fix":{"versions":["3.9.22","3.10.17","3.11.12","3.12.9","3.13.2","3.14.0a5"],"state":"fixed"},"advisories":[],"risk":0.5870349999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2025-0938","versionConstraint":"< 3.9.22,>= 3.10.0, < 3.10.17,>= 3.11.0, < 3.11.12,>= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.17"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4032","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4032","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml","http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"],"description":"The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4032","epss":0.00526,"percentile":0.66093,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0a6"],"state":"fixed"},"advisories":[],"risk":0.39449999999999996},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-4032","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0a6,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"59.6.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"332b7935715e95be","name":"setuptools","version":"59.6.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:59.6.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@59.6.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"75.8.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"27a37cc2ab306315","name":"setuptools","version":"75.8.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-75.8.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-75.8.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-75.8.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-75.8.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-75.8.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-75.8.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:75.8.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@75.8.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-0397","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0397","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/2","https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d","https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524","https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e","https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286","https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa","https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab","https://github.com/python/cpython/issues/114572","https://github.com/python/cpython/pull/114573","https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/","http://www.openwall.com/lists/oss-security/2024/06/17/2","https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d","https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524","https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e","https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286","https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa","https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab","https://github.com/python/cpython/issues/114572","https://github.com/python/cpython/pull/114573","https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/","https://security.netapp.com/advisory/ntap-20250411-0006/"],"description":"A defect was discovered in the Python “ssl” module where there is a memory\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\n“get_ca_certs()”. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0397","epss":0.00393,"percentile":0.5951,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.14","3.11.9","3.12.3","3.13.0a5"],"state":"fixed"},"advisories":[],"risk":0.292785},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-0397","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.9,>= 3.12.0, < 3.12.3,>= 3.13.0a1, < 3.13.0a5,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.14"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54322,"date":"2025-06-02"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54322,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"59.6.0"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"332b7935715e95be","name":"setuptools","version":"59.6.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:59.6.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@59.6.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-7592","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-7592","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/391e5626e3ee5af267b97e37abc7475732e67621","https://github.com/python/cpython/commit/44e458357fca05ca0ae2658d62c8c595b048b5ef","https://github.com/python/cpython/commit/a77ab24427a18bff817025adb03ca920dc3f1a06","https://github.com/python/cpython/commit/b2f11ca7667e4d57c71c1c88b255115f16042d9a","https://github.com/python/cpython/commit/d4ac921a4b081f7f996a5d2b101684b67ba0ed7f","https://github.com/python/cpython/commit/d662e2db2605515a767f88ad48096b8ac623c774","https://github.com/python/cpython/commit/dcc3eaef98cd94d6cb6cb0f44bd1c903d04f33b1","https://github.com/python/cpython/issues/123067","https://github.com/python/cpython/pull/123075","https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/","https://security.netapp.com/advisory/ntap-20241018-0006/"],"description":"There is a LOW severity vulnerability affecting CPython, specifically the\n'http.cookies' standard library module.\n\n\nWhen parsing cookies that contained backslashes for quoted characters in\nthe cookie value, the parser would use an algorithm with quadratic\ncomplexity, resulting in excess CPU resources being used while parsing the\nvalue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-7592","epss":0.00255,"percentile":0.49012,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.19125},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-7592","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"59.6.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"332b7935715e95be","name":"setuptools","version":"59.6.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/setuptools-59.6.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:59.6.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@59.6.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-40217","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-40217","namespace":"nvd:cpe","severity":"Medium","urls":["https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/","https://security.netapp.com/advisory/ntap-20231006-0014/","https://www.python.org/dev/security/","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/","https://security.netapp.com/advisory/ntap-20231006-0014/","https://www.python.org/dev/security/"],"description":"An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-40217","epss":0.00284,"percentile":0.51662,"date":"2025-06-02"}],"fix":{"versions":["3.8.18","3.9.18","3.10.13","3.11.5"],"state":"fixed"},"advisories":[],"risk":0.14626},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-40217","versionConstraint":"< 3.8.18,>= 3.10.0, < 3.10.13,>= 3.11.0, < 3.11.5,>= 3.9.0, < 3.9.18 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.13"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-34156","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34156","namespace":"nvd:cpe","severity":"High","urls":["https://go.dev/cl/611239","https://go.dev/issue/69139","https://groups.google.com/g/golang-dev/c/S9POB9NCTdk","https://pkg.go.dev/vuln/GO-2024-3106","https://security.netapp.com/advisory/ntap-20240926-0004/"],"description":"Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion. This is a follow-up to CVE-2022-30635.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34156","epss":0.00139,"percentile":0.35232,"date":"2025-06-02"}],"fix":{"versions":["1.22.7","1.23.1"],"state":"fixed"},"advisories":[],"risk":0.10425000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2024-34156","versionConstraint":"< 1.22.7,>= 1.23.0-0, < 1.23.1 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.22.7"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}},{"vulnerability":{"id":"CVE-2024-0450","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0450","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/30fe5d853b56138dbec62432d370a1f99409fc85","https://github.com/python/cpython/commit/66363b9a7b9fe7c99eba3a185b74c5fdbf842eba","https://github.com/python/cpython/commit/70497218351ba44bffc8b571201ecb5652d84675","https://github.com/python/cpython/commit/a2c59992e9e8d35baba9695eb186ad6c6ff85c51","https://github.com/python/cpython/commit/a956e510f6336d5ae111ba429a61c3ade30a7549","https://github.com/python/cpython/commit/d05bac0b74153beb541b88b4fca33bf053990183","https://github.com/python/cpython/commit/fa181fcf2156f703347b03a3b1966ce47be8ab3b","https://github.com/python/cpython/issues/109858","https://lists.debian.org/debian-lts-announce/2024/03/msg00024.html","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/XELNUX2L3IOHBTFU7RQHCY6OUVEWZ2FG/","https://www.bamsoftware.com/hacks/zipbomb/","http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/30fe5d853b56138dbec62432d370a1f99409fc85","https://github.com/python/cpython/commit/66363b9a7b9fe7c99eba3a185b74c5fdbf842eba","https://github.com/python/cpython/commit/70497218351ba44bffc8b571201ecb5652d84675","https://github.com/python/cpython/commit/a2c59992e9e8d35baba9695eb186ad6c6ff85c51","https://github.com/python/cpython/commit/a956e510f6336d5ae111ba429a61c3ade30a7549","https://github.com/python/cpython/commit/d05bac0b74153beb541b88b4fca33bf053990183","https://github.com/python/cpython/commit/fa181fcf2156f703347b03a3b1966ce47be8ab3b","https://github.com/python/cpython/issues/109858","https://lists.debian.org/debian-lts-announce/2024/03/msg00024.html","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/XELNUX2L3IOHBTFU7RQHCY6OUVEWZ2FG/","https://security.netapp.com/advisory/ntap-20250411-0005/","https://www.bamsoftware.com/hacks/zipbomb/"],"description":"An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0450","epss":0.00173,"percentile":0.3959,"date":"2025-06-02"}],"fix":{"versions":["3.8.19","3.9.19","3.10.14","3.11.8","3.12.2","3.13.0a3"],"state":"fixed"},"advisories":[],"risk":0.09688000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-0450","versionConstraint":"< 3.8.19,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.8,>= 3.12.0, < 3.12.2,>= 3.13.0a1, < 3.13.0a3,>= 3.9.0, < 3.9.19 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.14"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-qwmp-2cf2-g9g6","dataSource":"https://github.com/advisories/GHSA-qwmp-2cf2-g9g6","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/wheel vulnerable to Regular Expression denial of service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30277,"date":"2025-06-02"}],"fix":{"versions":["0.38.1"],"state":"fixed"},"advisories":[],"risk":0.08099999999999999},"relatedVulnerabilities":[{"id":"CVE-2022-40898","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40898","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"],"description":"An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30277,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"wheel","version":"0.37.1"}},"found":{"versionConstraint":"<0.38.1 (python)","vulnerabilityID":"GHSA-qwmp-2cf2-g9g6"},"fix":{"suggestedVersion":"0.38.1"}}],"artifact":{"id":"1afa9bd67344e5f4","name":"wheel","version":"0.37.1","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/wheel-0.37.1.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/wheel-0.37.1.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/wheel-0.37.1.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/wheel-0.37.1.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:daniel_holth_project:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python-wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python_wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:dholth:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:python:wheel:0.37.1:*:*:*:*:*:*:*","cpe:2.3:a:wheel:wheel:0.37.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/wheel@0.37.1","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-11168","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-11168","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/29f348e232e82938ba2165843c448c2b291504c5","https://github.com/python/cpython/commit/634ded45545ce8cbd6fd5d49785613dd7fa9b89e","https://github.com/python/cpython/commit/b2171a2fd41416cf68afd67460578631d755a550","https://github.com/python/cpython/commit/ddca2953191c67a12b1f19d6bca41016c6ae7132","https://github.com/python/cpython/issues/103848","https://github.com/python/cpython/pull/103849","https://mail.python.org/archives/list/security-announce@python.org/thread/XPWB6XVZ5G5KGEI63M4AWLIEUF5BPH4T/","https://security.netapp.com/advisory/ntap-20250411-0004/"],"description":"The urllib.parse.urlsplit() and urlparse() functions improperly validated bracketed hosts (`[]`), allowing hosts that weren't IPv6 or IPvFuture. This behavior was not conformant to RFC 3986 and potentially enabled SSRF if a URL is processed by more than one URL parser.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:N/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.7,"exploitabilityScore":2.3,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-11168","epss":0.00154,"percentile":0.3733,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.4","3.12.0b1"],"state":"fixed"},"advisories":[],"risk":0.077},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-11168","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.4,>= 3.12.0a1, < 3.12.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.16"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-rp8m-h266-53jh","dataSource":"https://github.com/advisories/GHSA-rp8m-h266-53jh","namespace":"github:language:python","severity":"Medium","urls":[],"description":"python-apt Flawed Package Integrity Check","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-15795","epss":0.00127,"percentile":0.33411,"date":"2025-06-02"}],"fix":{"versions":["0.8.3ubuntu7.5"],"state":"fixed"},"advisories":[],"risk":0.061595},"relatedVulnerabilities":[{"id":"CVE-2019-15795","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-15795","namespace":"nvd:cpe","severity":"Medium","urls":["https://usn.ubuntu.com/4247-1/","https://usn.ubuntu.com/4247-3/","https://usn.ubuntu.com/4247-1/","https://usn.ubuntu.com/4247-3/"],"description":"python-apt only checks the MD5 sums of downloaded files in `Version.fetch_binary()` and `Version.fetch_source()` of apt/package.py in version 1.9.0ubuntu1 and earlier. This allows a man-in-the-middle attack which could potentially be used to install altered packages and has been fixed in versions 1.9.0ubuntu1.2, 1.6.5ubuntu0.1, 1.1.0~beta1ubuntu0.16.04.7, 0.9.3.5ubuntu3+esm2, and 0.8.3ubuntu7.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:H/Au:N/C:N/I:P/A:N","metrics":{"baseScore":2.6,"exploitabilityScore":5,"impactScore":2.9},"vendorMetadata":{}},{"source":"security@ubuntu.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-15795","epss":0.00127,"percentile":0.33411,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"python-apt","version":"0.0.0"}},"found":{"versionConstraint":"<0.8.3ubuntu7.5 (unknown)","vulnerabilityID":"GHSA-rp8m-h266-53jh"},"fix":{"suggestedVersion":"0.8.3ubuntu7.5"}}],"artifact":{"id":"f9747a53c9006a57","name":"python-apt","version":"0.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/direct_url.json","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/direct_url.json","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["GNU GPL"],"cpes":["cpe:2.3:a:apt_development_team_project:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_team_project:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_teamproject:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_teamproject:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_team:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_team:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity_project:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity_project:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deityproject:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deityproject:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-apt:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-apt:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_apt:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_apt:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity:python_apt:0.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/python-apt@0.0.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-27043","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-27043","namespace":"nvd:cpe","severity":"Medium","urls":["http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/","http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/"],"description":"The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-27043","epss":0.00115,"percentile":0.31358,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0a1"],"state":"fixed"},"advisories":[],"risk":0.059225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-27043","versionConstraint":"< 3.8.20,>= 3.10.0a0, < 3.10.15,>= 3.11.0a0, < 3.11.10,>= 3.12.0a0, < 3.12.6,>= 3.13.0a0, < 3.13.0a1,>= 3.9.0a0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-pj65-3pf6-c5q4","dataSource":"https://github.com/advisories/GHSA-pj65-3pf6-c5q4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"python-apt Does Not Check Hash Signature","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-15796","epss":0.0012,"percentile":0.32166,"date":"2025-06-02"}],"fix":{"versions":["0.8.3ubuntu7.5"],"state":"fixed"},"advisories":[],"risk":0.058199999999999995},"relatedVulnerabilities":[{"id":"CVE-2019-15796","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-15796","namespace":"nvd:cpe","severity":"Medium","urls":["https://usn.ubuntu.com/4247-1/","https://usn.ubuntu.com/4247-3/","https://usn.ubuntu.com/4247-1/","https://usn.ubuntu.com/4247-3/"],"description":"Python-apt doesn't check if hashes are signed in `Version.fetch_binary()` and `Version.fetch_source()` of apt/package.py or in `_fetch_archives()` of apt/cache.py in version 1.9.3ubuntu2 and earlier. This allows downloads from unsigned repositories which shouldn't be allowed and has been fixed in verisions 1.9.5, 1.9.0ubuntu1.2, 1.6.5ubuntu0.1, 1.1.0~beta1ubuntu0.16.04.7, 0.9.3.5ubuntu3+esm2, and 0.8.3ubuntu7.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:H/Au:N/C:N/I:P/A:N","metrics":{"baseScore":2.6,"exploitabilityScore":5,"impactScore":2.9},"vendorMetadata":{}},{"source":"security@ubuntu.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-15796","epss":0.0012,"percentile":0.32166,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"python-apt","version":"0.0.0"}},"found":{"versionConstraint":"<0.8.3ubuntu7.5 (unknown)","vulnerabilityID":"GHSA-pj65-3pf6-c5q4"},"fix":{"suggestedVersion":"0.8.3ubuntu7.5"}}],"artifact":{"id":"f9747a53c9006a57","name":"python-apt","version":"0.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/direct_url.json","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/direct_url.json","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/python_apt-0.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["GNU GPL"],"cpes":["cpe:2.3:a:apt_development_team_project:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_team_project:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_teamproject:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_teamproject:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_team:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:apt_development_team:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity_project:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity_project:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deityproject:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deityproject:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-apt:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-apt:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_apt:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_apt:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity:python-apt:0.0.0:*:*:*:*:*:*:*","cpe:2.3:a:deity:python_apt:0.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/python-apt@0.0.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-8088","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-8088","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/0aa1ee22ab6e204e9d3d0e9dd63ea648ed691ef1","https://github.com/python/cpython/commit/2231286d78d328c2f575e0b05b16fe447d1656d6","https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e","https://github.com/python/cpython/commit/7bc367e464ce50b956dd232c1dfa1cad4e7fb814","https://github.com/python/cpython/commit/7e8883a3f04d308302361aeffc73e0e9837f19d4","https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64","https://github.com/python/cpython/commit/95b073bddefa6243effa08e131e297c0383e7f6a","https://github.com/python/cpython/commit/962055268ed4f2ca1d717bfc8b6385de50a23ab7","https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea","https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db","https://github.com/python/cpython/commit/fc0b8259e693caa8400fa8b6ac1e494e47ea7798","https://github.com/python/cpython/issues/122905","https://github.com/python/cpython/issues/123270","https://github.com/python/cpython/pull/122906","https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/","http://www.openwall.com/lists/oss-security/2024/08/22/1","http://www.openwall.com/lists/oss-security/2024/08/22/4","http://www.openwall.com/lists/oss-security/2024/08/23/1","http://www.openwall.com/lists/oss-security/2024/08/23/2","https://security.netapp.com/advisory/ntap-20241011-0010/"],"description":"There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:N/AU:N/R:U/V:X/RE:L/U:X","metrics":{"baseScore":8.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-8088","epss":0.00071,"percentile":0.22529,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.05750999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-8088","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-6597","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-6597","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a","https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25","https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5","https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d","https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82","https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b","https://github.com/python/cpython/issues/91133","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/","http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a","https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25","https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5","https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d","https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82","https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b","https://github.com/python/cpython/issues/91133","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/"],"description":"An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N","metrics":{"baseScore":7.8,"exploitabilityScore":1.5,"impactScore":5.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-6597","epss":0.00073,"percentile":0.23139,"date":"2025-06-02"}],"fix":{"versions":["3.8.19","3.9.19","3.10.14","3.11.8","3.12.1","3.13.0a3"],"state":"fixed"},"advisories":[],"risk":0.05584499999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-6597","versionConstraint":"< 3.8.19,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.8,>= 3.12.0, < 3.12.1,>= 3.13.0a1, < 3.13.0a3,>= 3.9.0, < 3.9.19 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.14"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-6923","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6923","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/06f28dc236708f72871c64d4bc4b4ea144c50147","https://github.com/python/cpython/commit/097633981879b3c9de9a1dd120d3aa585ecc2384","https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7","https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0","https://github.com/python/cpython/commit/b158a76ce094897c870fb6b3de62887b7ccc33f1","https://github.com/python/cpython/commit/f7be505d137a22528cb0fc004422c0081d5d90e6","https://github.com/python/cpython/commit/f7c0f09e69e950cf3c5ada9dbde93898eb975533","https://github.com/python/cpython/issues/121650","https://github.com/python/cpython/pull/122233","https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/","http://www.openwall.com/lists/oss-security/2024/08/01/3","http://www.openwall.com/lists/oss-security/2024/08/02/2","https://lists.debian.org/debian-lts-announce/2025/01/msg00005.html","https://security.netapp.com/advisory/ntap-20240926-0003/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":5.5,"exploitabilityScore":2.1,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6923","epss":0.00089,"percentile":0.26707,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.046725},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-6923","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-34158","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34158","namespace":"nvd:cpe","severity":"High","urls":["https://go.dev/cl/611240","https://go.dev/issue/69141","https://groups.google.com/g/golang-dev/c/S9POB9NCTdk","https://pkg.go.dev/vuln/GO-2024-3107","https://security.netapp.com/advisory/ntap-20241004-0003/"],"description":"Calling Parse on a \"// +build\" build tag line with deeply nested expressions can cause a panic due to stack exhaustion.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34158","epss":0.00062,"percentile":0.19568,"date":"2025-06-02"}],"fix":{"versions":["1.22.7","1.23.1"],"state":"fixed"},"advisories":[],"risk":0.0465},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2024-34158","versionConstraint":"< 1.22.7,>= 1.23.0-0, < 1.23.1 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.22.7"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}},{"vulnerability":{"id":"CVE-2025-1795","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-1795","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/python/cpython/commit/09fab93c3d857496c0bd162797fab816c311ee48","https://github.com/python/cpython/commit/70754d21c288535e86070ca7a6e90dcb670b8593","https://github.com/python/cpython/commit/9148b77e0af91cdacaa7fe3dfac09635c3fe9a74","https://github.com/python/cpython/issues/100884","https://github.com/python/cpython/pull/100885","https://github.com/python/cpython/pull/119099","https://mail.python.org/archives/list/security-announce@python.org/thread/MB62IZMEC3UM6SGHP5LET5JX2Y7H4ZUR/"],"description":"During an address list folding when a separating comma ends up on a folded line and that line is to be unicode-encoded then the separator itself is also unicode-encoded. Expected behavior is that the separating comma remains a plan comma. This can result in the address header being misinterpreted by some mail servers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:L/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-1795","epss":0.00167,"percentile":0.38934,"date":"2025-06-02"}],"fix":{"versions":["3.11.9","3.12.3","3.13.0a5"],"state":"fixed"},"advisories":[],"risk":0.044255},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2025-1795","versionConstraint":"< 3.11.9,>= 3.12.0, < 3.12.3,>= 3.13.0a1, < 3.13.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.11.9"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-34155","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34155","namespace":"nvd:cpe","severity":"Medium","urls":["https://go.dev/cl/611238","https://go.dev/issue/69138","https://groups.google.com/g/golang-dev/c/S9POB9NCTdk","https://pkg.go.dev/vuln/GO-2024-3105","https://security.netapp.com/advisory/ntap-20240926-0005/"],"description":"Calling any of the Parse functions on Go source code which contains deeply nested literals can cause a panic due to stack exhaustion.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":4.3,"exploitabilityScore":2.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34155","epss":0.0009,"percentile":0.26978,"date":"2025-06-02"}],"fix":{"versions":["1.22.7","1.23.1"],"state":"fixed"},"advisories":[],"risk":0.04185},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2024-34155","versionConstraint":"< 1.22.7,>= 1.23.0-0, < 1.23.1 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.22.7"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}},{"vulnerability":{"id":"GHSA-hcg3-q754-cr77","dataSource":"https://github.com/advisories/GHSA-hcg3-q754-cr77","namespace":"github:language:go","severity":"High","urls":[],"description":"golang.org/x/crypto Vulnerable to Denial of Service (DoS) via Slow or Incomplete Key Exchange","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22869","epss":0.00051,"percentile":0.15901,"date":"2025-06-02"}],"fix":{"versions":["0.35.0"],"state":"fixed"},"advisories":[],"risk":0.038250000000000006},"relatedVulnerabilities":[{"id":"CVE-2025-22869","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-22869","namespace":"nvd:cpe","severity":"High","urls":["https://go.dev/cl/652135","https://go.dev/issue/71931","https://pkg.go.dev/vuln/GO-2025-3487","https://security.netapp.com/advisory/ntap-20250411-0010/"],"description":"SSH servers which implement file transfer protocols are vulnerable to a denial of service attack from clients which complete the key exchange slowly, or not at all, causing pending content to be read into memory, but never transmitted.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22869","epss":0.00051,"percentile":0.15901,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"go-module-matcher","searchedBy":{"language":"go","namespace":"github:language:go","package":{"name":"golang.org/x/crypto","version":"v0.32.0"}},"found":{"versionConstraint":"<0.35.0 (go)","vulnerabilityID":"GHSA-hcg3-q754-cr77"},"fix":{"suggestedVersion":"0.35.0"}}],"artifact":{"id":"dfc907c909cac92b","name":"golang.org/x/crypto","version":"v0.32.0","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":[],"cpes":["cpe:2.3:a:go:ssh:v0.32.0:*:*:*:*:go:*:*"],"purl":"pkg:golang/golang.org/x/crypto@v0.32.0","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":"amd64","h1Digest":"h1:euUpcYgM8WcP71gNpTqQCn6rC2t6ULUPiOzfWaXVVfc=","mainModule":"github.com/snapcore/spread"}}},{"vulnerability":{"id":"CVE-2024-3219","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3219","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/2621a8a40ba4b2c68ca564671b7daa5da80a4508","https://github.com/python/cpython/commit/31302f5fc24eecd693f0c8aaba7c2840b09b594d","https://github.com/python/cpython/commit/3f5d9d12c74787fbf3f5891835c85cc15526c86d","https://github.com/python/cpython/commit/5df322e91a40909e6904bbdbc0c3a6b6a9eead39","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/78df1043dbdce5c989600616f9f87b4ee72944e5","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/commit/c21a36112a0028d7ac3cf8f480e0dc88dba5922c","https://github.com/python/cpython/commit/c5655aa6ad120d2ed7f255bebd6e8b71a9c07dde","https://github.com/python/cpython/commit/e319f774f9e766a2b92949444a2d46081df3363a","https://github.com/python/cpython/commit/f071f01b7b7e19d7d6b3a4b0ec62f820ecb14660","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","https://security.netapp.com/advisory/ntap-20250502-0004/"],"description":"The\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.1},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3219","epss":0.00059,"percentile":0.18705,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc1"],"state":"fixed"},"advisories":[],"risk":0.029795000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-3219","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-9287","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-9287","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7","https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db","https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8","https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97","https://github.com/python/cpython/commit/d48cc82ed25e26b02eb97c6263d95dcaa1e9111b","https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483","https://github.com/python/cpython/issues/124651","https://github.com/python/cpython/pull/124712","https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/","https://security.netapp.com/advisory/ntap-20250425-0006/"],"description":"A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:Green","metrics":{"baseScore":5.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-9287","epss":0.00038,"percentile":0.10564,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1","3.14.0a2"],"state":"fixed"},"advisories":[],"risk":0.026695},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-9287","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.11,>= 3.12.0, < 3.12.8,>= 3.13.0, < 3.13.1,>= 3.14.0a1, < 3.14.0a2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.16"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3220","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3220","namespace":"nvd:cpe","severity":"Low","urls":["https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/","http://www.openwall.com/lists/oss-security/2025/02/14/8","https://security.netapp.com/advisory/ntap-20250314-0001/"],"description":"There is a defect in the CPython standard library module “mimetypes” where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as “/etc/mime.types”) also being used on Windows, where they are user-writable locations (“C:\\etc\\mime.types”).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (“[]”) on Windows platforms to avoid using the default list of known file locations.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3220","epss":0.00088,"percentile":0.26555,"date":"2025-06-02"}],"fix":{"versions":["3.14.0"],"state":"fixed"},"advisories":[],"risk":0.023320000000000004},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-3220","versionConstraint":"< 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-36632","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-36632","namespace":"nvd:cpe","severity":"High","urls":["https://docs.python.org/3/library/email.html","https://docs.python.org/3/library/email.utils.html","https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py","https://github.com/python/cpython/issues/103800","https://docs.python.org/3/library/email.html","https://docs.python.org/3/library/email.utils.html","https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py","https://github.com/python/cpython/issues/103800"],"description":"The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-36632","epss":0.0003,"percentile":0.07087,"date":"2025-06-02"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.0225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-36632","versionConstraint":"<= 3.11.4 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"22.0.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"39ff3db1d84e0f84","name":"pip","version":"22.0.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/pip-22.0.2.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/pip-22.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/pip-22.0.2.dist-info/RECORD","accessPath":"/usr/lib/python3/dist-packages/pip-22.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3/dist-packages/pip-22.0.2.dist-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/pip-22.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:22.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@22.0.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-50602","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-50602","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/libexpat/libexpat/pull/915","https://lists.debian.org/debian-lts-announce/2025/04/msg00040.html","https://security.netapp.com/advisory/ntap-20250404-0008/"],"description":"An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-50602","epss":0.00037,"percentile":0.10035,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1"],"state":"fixed"},"advisories":[],"risk":0.020165000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-50602","versionConstraint":"< 3.9.21,>= 3.10, < 3.10.16,>= 3.11, < 3.11.11,>= 3.12, < 3.12.8,>= 3.13, < 3.13.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.16"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-45336","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-45336","namespace":"nvd:cpe","severity":"Medium","urls":["https://go.dev/cl/643100","https://go.dev/issue/70530","https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ","https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ","https://pkg.go.dev/vuln/GO-2025-3420","https://security.netapp.com/advisory/ntap-20250221-0003/"],"description":"The HTTP client drops sensitive headers after following a cross-domain redirect. For example, a request to a.com/ containing an Authorization header which is redirected to b.com/ will not send that header to b.com. In the event that the client received a subsequent same-domain redirect, however, the sensitive headers would be restored. For example, a chain of redirects from a.com/, to b.com/1, and finally to b.com/2 would incorrectly send the Authorization header to b.com/2.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-45336","epss":0.00035,"percentile":0.08892,"date":"2025-06-02"}],"fix":{"versions":["1.22.11","1.23.5","1.24.0-rc.2"],"state":"fixed"},"advisories":[],"risk":0.019424999999999998},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2024-45336","versionConstraint":"< 1.22.11,>= 1.23.0-0, < 1.23.5,>= 1.24.0-0, < 1.24.0-rc.2 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.22.11"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}},{"vulnerability":{"id":"CVE-2025-22871","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-22871","namespace":"nvd:cpe","severity":"Critical","urls":["https://go.dev/cl/652998","https://go.dev/issue/71988","https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk","https://pkg.go.dev/vuln/GO-2025-3563","http://www.openwall.com/lists/oss-security/2025/04/04/4"],"description":"The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22871","epss":0.00018,"percentile":0.03232,"date":"2025-06-02"}],"fix":{"versions":["1.23.8","1.24.2"],"state":"fixed"},"advisories":[],"risk":0.01629},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2025-22871","versionConstraint":"< 1.23.8,>= 1.24.0-0, < 1.24.2 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.23.8"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}},{"vulnerability":{"id":"CVE-2024-45341","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-45341","namespace":"nvd:cpe","severity":"Medium","urls":["https://go.dev/cl/643099","https://go.dev/issue/71156","https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ","https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ","https://pkg.go.dev/vuln/GO-2025-3373","https://security.netapp.com/advisory/ntap-20250221-0004/"],"description":"A certificate with a URI which has a IPv6 address with a zone ID may incorrectly satisfy a URI name constraint that applies to the certificate chain. Certificates containing URIs are not permitted in the web PKI, so this only affects users of private PKIs which make use of URIs.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-45341","epss":0.00024,"percentile":0.04824,"date":"2025-06-02"}],"fix":{"versions":["1.22.11","1.23.5","1.24.0-rc.2"],"state":"fixed"},"advisories":[],"risk":0.013319999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2024-45341","versionConstraint":"< 1.22.11,>= 1.23.0-0, < 1.23.5,>= 1.24.0-0, < 1.24.0-rc.2 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.22.11"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}},{"vulnerability":{"id":"GHSA-vvgc-356p-c3xw","dataSource":"https://github.com/advisories/GHSA-vvgc-356p-c3xw","namespace":"github:language:go","severity":"Medium","urls":[],"description":"golang.org/x/net vulnerable to Cross-site Scripting","cvss":[],"epss":[{"cve":"CVE-2025-22872","epss":0.00024,"percentile":0.05071,"date":"2025-06-02"}],"fix":{"versions":["0.38.0"],"state":"fixed"},"advisories":[],"risk":0.012},"relatedVulnerabilities":[{"id":"CVE-2025-22872","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-22872","namespace":"nvd:cpe","severity":"Medium","urls":["https://go.dev/cl/662715","https://go.dev/issue/73070","https://groups.google.com/g/golang-announce/c/ezSKR9vqbqA","https://pkg.go.dev/vuln/GO-2025-3595","https://security.netapp.com/advisory/ntap-20250516-0007/"],"description":"The tokenizer incorrectly interprets tags with unquoted attribute values that end with a solidus character (/) as self-closing. When directly using Tokenizer, this can result in such tags incorrectly being marked as self-closing, and when using the Parse functions, this can result in content following such tags as being placed in the wrong scope during DOM construction, but only when tags are in foreign content (e.g. <math>, <svg>, etc contexts).","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":2.3,"impactScore":3.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22872","epss":0.00024,"percentile":0.05071,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"go-module-matcher","searchedBy":{"language":"go","namespace":"github:language:go","package":{"name":"golang.org/x/net","version":"v0.34.0"}},"found":{"versionConstraint":"<0.38.0 (go)","vulnerabilityID":"GHSA-vvgc-356p-c3xw"},"fix":{"suggestedVersion":"0.38.0"}}],"artifact":{"id":"8dcc31f4d3987325","name":"golang.org/x/net","version":"v0.34.0","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":[],"cpes":["cpe:2.3:a:golang:networking:v0.34.0:*:*:*:*:go:*:*"],"purl":"pkg:golang/golang.org/x/net@v0.34.0","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":"amd64","h1Digest":"h1:Mb7Mrk043xzHgnRM88suvJFwzVrRfHEHJEl5/71CKw0=","mainModule":"github.com/snapcore/spread"}}},{"vulnerability":{"id":"CVE-2024-4030","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4030","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/","https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/"],"description":"On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.\n\nIf you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.\n\nThis issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":7.1,"exploitabilityScore":1.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4030","epss":0.00014,"percentile":0.0153,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0b1"],"state":"fixed"},"advisories":[],"risk":0.01022},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-4030","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0b1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142","https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e","https://github.com/python/cpython/issues/133767","https://github.com/python/cpython/pull/129648","https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/","http://www.openwall.com/lists/oss-security/2025/05/16/4","http://www.openwall.com/lists/oss-security/2025/05/19/1"],"description":"There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:H/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4516","epss":0.00018,"percentile":0.03232,"date":"2025-06-02"}],"fix":{"versions":["3.14.0b1"],"state":"fixed"},"advisories":[],"risk":0.009810000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2025-4516","versionConstraint":"< 3.14.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0b1"}}],"artifact":{"id":"900f50b0e42955a6","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/usr/bin/python3.10","accessPath":"/usr/bin/python3.10","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-qxp5-gwg8-xv66","dataSource":"https://github.com/advisories/GHSA-qxp5-gwg8-xv66","namespace":"github:language:go","severity":"Medium","urls":[],"description":"HTTP Proxy bypass using IPv6 Zone IDs in golang.org/x/net","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:L","metrics":{"baseScore":4.4,"exploitabilityScore":1.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22870","epss":0.00012,"percentile":0.01243,"date":"2025-06-02"}],"fix":{"versions":["0.36.0"],"state":"fixed"},"advisories":[],"risk":0.00564},"relatedVulnerabilities":[{"id":"CVE-2025-22870","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-22870","namespace":"nvd:cpe","severity":"Medium","urls":["https://go.dev/cl/654697","https://go.dev/issue/71984","https://pkg.go.dev/vuln/GO-2025-3503","http://www.openwall.com/lists/oss-security/2025/03/07/2","https://security.netapp.com/advisory/ntap-20250509-0007/"],"description":"Matching of hosts against proxy patterns can improperly treat an IPv6 zone ID as a hostname component. For example, when the NO_PROXY environment variable is set to \"*.example.com\", a request to \"[::1%25.example.com]:80` will incorrectly match and not be proxied.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:L","metrics":{"baseScore":4.4,"exploitabilityScore":1.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22870","epss":0.00012,"percentile":0.01243,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"go-module-matcher","searchedBy":{"language":"go","namespace":"github:language:go","package":{"name":"golang.org/x/net","version":"v0.34.0"}},"found":{"versionConstraint":"<0.36.0 (go)","vulnerabilityID":"GHSA-qxp5-gwg8-xv66"},"fix":{"suggestedVersion":"0.36.0"}}],"artifact":{"id":"8dcc31f4d3987325","name":"golang.org/x/net","version":"v0.34.0","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":[],"cpes":["cpe:2.3:a:golang:networking:v0.34.0:*:*:*:*:go:*:*"],"purl":"pkg:golang/golang.org/x/net@v0.34.0","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":"amd64","h1Digest":"h1:Mb7Mrk043xzHgnRM88suvJFwzVrRfHEHJEl5/71CKw0=","mainModule":"github.com/snapcore/spread"}}},{"vulnerability":{"id":"CVE-2025-22866","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-22866","namespace":"nvd:cpe","severity":"Medium","urls":["https://go.dev/cl/643735","https://go.dev/issue/71383","https://groups.google.com/g/golang-announce/c/xU1ZCHUZw3k","https://pkg.go.dev/vuln/GO-2025-3447","https://security.netapp.com/advisory/ntap-20250221-0002/"],"description":"Due to the usage of a variable time instruction in the assembly implementation of an internal function, a small number of bits of secret scalars are leaked on the ppc64le architecture. Due to the way this function is used, we do not believe this leakage is enough to allow recovery of the private key when P-256 is used in any well known protocols.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N","metrics":{"baseScore":4,"exploitabilityScore":2.6,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-22866","epss":0.00009,"percentile":0.0056,"date":"2025-06-02"}],"fix":{"versions":["1.22.12","1.23.6","1.24.0-rc.3"],"state":"fixed"},"advisories":[],"risk":0.00405},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"go-module-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"package":{"name":"stdlib","version":"go1.21.13"}},"found":{"vulnerabilityID":"CVE-2025-22866","versionConstraint":"< 1.22.12,>= 1.23.0-0, < 1.23.6,>= 1.24.0-0, < 1.24.0-rc.3 (unknown)","cpes":["cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"1.22.12"}}],"artifact":{"id":"33701f8fb1d19f4c","name":"stdlib","version":"go1.21.13","type":"go-module","locations":[{"path":"/bin/spread","accessPath":"/bin/spread","annotations":{"evidence":"primary"}}],"language":"go","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:golang:go:1.21.13:-:*:*:*:*:*:*"],"purl":"pkg:golang/stdlib@1.21.13","upstreams":[],"metadataType":"GolangBinMetadata","metadata":{"goCompiledVersion":"go1.21.13","architecture":""}}}],"source":{"type":"sbom-file","target":"charmcraft-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/charmcraft-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/charmcraft-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T17:56:50.91847+01:00"}}
