{"matches":[{"vulnerability":{"id":"CVE-2024-6232","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6232","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/34ddb64d088dd7ccc321f6103d23153256caa5d4","https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06","https://github.com/python/cpython/commit/743acbe872485dc18df4d8ab2dc7895187f062c4","https://github.com/python/cpython/commit/7d1f50cd92ff7e10a1c15a8f591dde8a6843a64d","https://github.com/python/cpython/commit/b4225ca91547aa97ed3aca391614afbb255bc877","https://github.com/python/cpython/commit/d449caf8a179e3b954268b3a88eb9170be3c8fbf","https://github.com/python/cpython/commit/ed3a49ea734ada357ff4442996fd4ae71d253373","https://github.com/python/cpython/issues/121285","https://github.com/python/cpython/pull/121286","https://mail.python.org/archives/list/security-announce@python.org/thread/JRYFTPRHZRTLMZLWQEUHZSJXNHM4ACTY/","http://www.openwall.com/lists/oss-security/2024/09/03/5","https://security.netapp.com/advisory/ntap-20241018-0007/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\n\n\n\n\nRegular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6232","epss":0.00834,"percentile":0.73563,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.6255000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-6232","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.6"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-0938","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-0938","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/526617ed68cde460236c973e5d0a8bad4de896ba","https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403","https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568","https://github.com/python/cpython/commit/b8b4b713c5f8ec0958c7ef8d29d6711889bc94ab","https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a","https://github.com/python/cpython/commit/ff4e5c25666f63544071a6b075ae8b25c98b7a32","https://github.com/python/cpython/issues/105704","https://github.com/python/cpython/pull/129418","https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/","https://security.netapp.com/advisory/ntap-20250314-0002/"],"description":"The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-0938","epss":0.01039,"percentile":0.76414,"date":"2025-06-02"}],"fix":{"versions":["3.9.22","3.10.17","3.11.12","3.12.9","3.13.2","3.14.0a5"],"state":"fixed"},"advisories":[],"risk":0.5870349999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2025-0938","versionConstraint":"< 3.9.22,>= 3.10.0, < 3.10.17,>= 3.11.0, < 3.11.12,>= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.9"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-248v-346w-9cwc","dataSource":"https://github.com/advisories/GHSA-248v-346w-9cwc","namespace":"github:language:python","severity":"Low","urls":[],"description":"Certifi removes GLOBALTRUST root certificate","cvss":[],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82506,"date":"2025-06-02"}],"fix":{"versions":["2024.7.4"],"state":"fixed"},"advisories":[],"risk":0.5783999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-39689","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://security.netapp.com/advisory/ntap-20241206-0001/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82506,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2023.11.17"}},"found":{"versionConstraint":">=2021.5.30,<2024.7.4 (python)","vulnerabilityID":"GHSA-248v-346w-9cwc"},"fix":{"suggestedVersion":"2024.7.4"}}],"artifact":{"id":"d84e7ba6c3591729","name":"certifi","version":"2023.11.17","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/certifi-2023.11.17.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/certifi-2023.11.17.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/certifi-2023.11.17.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/certifi-2023.11.17.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2023.11.17:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2023.11.17","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4032","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4032","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml","http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"],"description":"The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4032","epss":0.00526,"percentile":0.66093,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0a6"],"state":"fixed"},"advisories":[],"risk":0.39449999999999996},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-4032","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0a6,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.4"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.65933,"date":"2025-06-02"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.65933,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"4fb75bcf5cd65cf7","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.65933,"date":"2025-06-02"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.65933,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"10851c6f62cd71db","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62112,"date":"2025-06-02"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62112,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"3.6"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"fbb605a03fc1740e","name":"idna","version":"3.6","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/idna-3.6.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/idna-3.6.dist-info/METADATA","annotations":{"evidence":"primary"}}],"language":"python","licenses":[],"cpes":["cpe:2.3:a:kim_davies_<kim+pypi_project:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi_project:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypiproject:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypiproject:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi_project:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim+pypi:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim+pypi:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypiproject:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim+pypi:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:3.6:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@3.6","upstreams":[]}},{"vulnerability":{"id":"GHSA-6vqw-3v5j-54x4","dataSource":"https://github.com/advisories/GHSA-6vqw-3v5j-54x4","namespace":"github:language:python","severity":"High","urls":[],"description":"cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49168,"date":"2025-06-02"}],"fix":{"versions":["42.0.4"],"state":"fixed"},"advisories":[],"risk":0.19275},"relatedVulnerabilities":[{"id":"CVE-2024-26130","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-26130","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4","https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49168,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":">=38.0.0,<42.0.4 (python)","vulnerabilityID":"GHSA-6vqw-3v5j-54x4"},"fix":{"suggestedVersion":"42.0.4"}}],"artifact":{"id":"4fb75bcf5cd65cf7","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-6vqw-3v5j-54x4","dataSource":"https://github.com/advisories/GHSA-6vqw-3v5j-54x4","namespace":"github:language:python","severity":"High","urls":[],"description":"cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49168,"date":"2025-06-02"}],"fix":{"versions":["42.0.4"],"state":"fixed"},"advisories":[],"risk":0.19275},"relatedVulnerabilities":[{"id":"CVE-2024-26130","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-26130","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4","https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49168,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":">=38.0.0,<42.0.4 (python)","vulnerabilityID":"GHSA-6vqw-3v5j-54x4"},"fix":{"suggestedVersion":"42.0.4"}}],"artifact":{"id":"10851c6f62cd71db","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-7592","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-7592","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/391e5626e3ee5af267b97e37abc7475732e67621","https://github.com/python/cpython/commit/44e458357fca05ca0ae2658d62c8c595b048b5ef","https://github.com/python/cpython/commit/a77ab24427a18bff817025adb03ca920dc3f1a06","https://github.com/python/cpython/commit/b2f11ca7667e4d57c71c1c88b255115f16042d9a","https://github.com/python/cpython/commit/d4ac921a4b081f7f996a5d2b101684b67ba0ed7f","https://github.com/python/cpython/commit/d662e2db2605515a767f88ad48096b8ac623c774","https://github.com/python/cpython/commit/dcc3eaef98cd94d6cb6cb0f44bd1c903d04f33b1","https://github.com/python/cpython/issues/123067","https://github.com/python/cpython/pull/123075","https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/","https://security.netapp.com/advisory/ntap-20241018-0006/"],"description":"There is a LOW severity vulnerability affecting CPython, specifically the\n'http.cookies' standard library module.\n\n\nWhen parsing cookies that contained backslashes for quoted characters in\nthe cookie value, the parser would use an algorithm with quadratic\ncomplexity, resulting in excess CPU resources being used while parsing the\nvalue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-7592","epss":0.00255,"percentile":0.49012,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.19125},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-7592","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.6"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-12254","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-12254","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/71e8429ac8e2adc10084ab5ec29a62f4b6671a82","https://github.com/python/cpython/commit/9aa0deb2eef2655a1029ba228527b152353135b5","https://github.com/python/cpython/commit/e991ac8f2037d78140e417cc9a9486223eb3e786","https://github.com/python/cpython/issues/127655","https://github.com/python/cpython/pull/127656","https://mail.python.org/archives/list/security-announce@python.org/thread/H4O3UBAOAQQXGT4RE3E4XQYR5XLROORB/","http://www.openwall.com/lists/oss-security/2024/12/06/1","https://security.netapp.com/advisory/ntap-20250404-0010/"],"description":"Starting in Python 3.12.0, the asyncio._SelectorSocketTransport.writelines()\n method would not \"pause\" writing and signal to the Protocol to drain \nthe buffer to the wire once the write buffer reached the \"high-water \nmark\". Because of this, Protocols would not periodically drain the write\n buffer potentially leading to memory exhaustion.\n\n\n\n\n\nThis\n vulnerability likely impacts a small number of users, you must be using\n Python 3.12.0 or later, on macOS or Linux, using the asyncio module \nwith protocols, and using .writelines() method which had new \nzero-copy-on-write behavior in Python 3.12.0 and later. If not all of \nthese factors are true then your usage of Python is unaffected.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":8.7},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-12254","epss":0.00144,"percentile":0.35961,"date":"2025-06-02"}],"fix":{"versions":["3.12.9","3.13.2","3.14.0a3"],"state":"fixed"},"advisories":[],"risk":0.11232000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-12254","versionConstraint":">= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a3 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.9"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-q2x7-8rv6-6q7h","dataSource":"https://github.com/advisories/GHSA-q2x7-8rv6-6q7h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through indirect reference to format method","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.06592},"relatedVulnerabilities":[{"id":"CVE-2024-56326","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56326","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/48b0687e05a5466a91cd5812d604fa37ad0943b4","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-q2x7-8rv6-6q7h"],"description":"Jinja is an extensible templating engine. Prior to 3.1.5, An oversight in how the Jinja sandboxed environment detects calls to str.format allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to store a reference to a malicious string's format method, then pass that to a filter that calls it. No such filters are built-in to Jinja, but could be present through custom filters in an application. After the fix, such indirect calls are also handled by the sandbox. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.2"}},"found":{"versionConstraint":"<=3.1.4 (python)","vulnerabilityID":"GHSA-q2x7-8rv6-6q7h"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"9ee154135ba244b0","name":"jinja2","version":"3.1.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-27043","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-27043","namespace":"nvd:cpe","severity":"Medium","urls":["http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/","http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/"],"description":"The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-27043","epss":0.00115,"percentile":0.31358,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0a1"],"state":"fixed"},"advisories":[],"risk":0.059225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2023-27043","versionConstraint":"< 3.8.20,>= 3.10.0a0, < 3.10.15,>= 3.11.0a0, < 3.11.10,>= 3.12.0a0, < 3.12.6,>= 3.13.0a0, < 3.13.0a1,>= 3.9.0a0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.6"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-8088","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-8088","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/0aa1ee22ab6e204e9d3d0e9dd63ea648ed691ef1","https://github.com/python/cpython/commit/2231286d78d328c2f575e0b05b16fe447d1656d6","https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e","https://github.com/python/cpython/commit/7bc367e464ce50b956dd232c1dfa1cad4e7fb814","https://github.com/python/cpython/commit/7e8883a3f04d308302361aeffc73e0e9837f19d4","https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64","https://github.com/python/cpython/commit/95b073bddefa6243effa08e131e297c0383e7f6a","https://github.com/python/cpython/commit/962055268ed4f2ca1d717bfc8b6385de50a23ab7","https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea","https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db","https://github.com/python/cpython/commit/fc0b8259e693caa8400fa8b6ac1e494e47ea7798","https://github.com/python/cpython/issues/122905","https://github.com/python/cpython/issues/123270","https://github.com/python/cpython/pull/122906","https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/","http://www.openwall.com/lists/oss-security/2024/08/22/1","http://www.openwall.com/lists/oss-security/2024/08/22/4","http://www.openwall.com/lists/oss-security/2024/08/23/1","http://www.openwall.com/lists/oss-security/2024/08/23/2","https://security.netapp.com/advisory/ntap-20241011-0010/"],"description":"There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:N/AU:N/R:U/V:X/RE:L/U:X","metrics":{"baseScore":8.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-8088","epss":0.00071,"percentile":0.22529,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.05750999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-8088","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.6"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29442,"date":"2025-06-02"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29442,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"4fb75bcf5cd65cf7","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29442,"date":"2025-06-02"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29442,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"10851c6f62cd71db","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-h5c8-rqwp-cp95","dataSource":"https://github.com/advisories/GHSA-h5c8-rqwp-cp95","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-22195","epss":0.00102,"percentile":0.29274,"date":"2025-06-02"}],"fix":{"versions":["3.1.3"],"state":"fixed"},"advisories":[],"risk":0.05304000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-22195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-22195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/releases/tag/3.1.3","https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95","https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/","https://github.com/pallets/jinja/releases/tag/3.1.3","https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95","https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/"],"description":"Jinja is an extensible templating engine. Special placeholders in the template allow writing code similar to Python syntax. It is possible to inject arbitrary HTML attributes into the rendered HTML template, potentially leading to Cross-Site Scripting (XSS). The Jinja `xmlattr` filter can be abused to inject arbitrary HTML attribute keys and values, bypassing the auto escaping mechanism and potentially leading to XSS. It may also be possible to bypass attribute validation checks if they are blacklist-based.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-22195","epss":0.00102,"percentile":0.29274,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.2"}},"found":{"versionConstraint":"<3.1.3 (python)","vulnerabilityID":"GHSA-h5c8-rqwp-cp95"},"fix":{"suggestedVersion":"3.1.3"}}],"artifact":{"id":"9ee154135ba244b0","name":"jinja2","version":"3.1.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-6923","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6923","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/06f28dc236708f72871c64d4bc4b4ea144c50147","https://github.com/python/cpython/commit/097633981879b3c9de9a1dd120d3aa585ecc2384","https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7","https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0","https://github.com/python/cpython/commit/b158a76ce094897c870fb6b3de62887b7ccc33f1","https://github.com/python/cpython/commit/f7be505d137a22528cb0fc004422c0081d5d90e6","https://github.com/python/cpython/commit/f7c0f09e69e950cf3c5ada9dbde93898eb975533","https://github.com/python/cpython/issues/121650","https://github.com/python/cpython/pull/122233","https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/","http://www.openwall.com/lists/oss-security/2024/08/01/3","http://www.openwall.com/lists/oss-security/2024/08/02/2","https://lists.debian.org/debian-lts-announce/2025/01/msg00005.html","https://security.netapp.com/advisory/ntap-20240926-0003/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":5.5,"exploitabilityScore":2.1,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6923","epss":0.00089,"percentile":0.26707,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.046725},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-6923","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.5"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-h75v-3vvj-5mfj","dataSource":"https://github.com/advisories/GHSA-h75v-3vvj-5mfj","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34064","epss":0.00085,"percentile":0.25888,"date":"2025-06-02"}],"fix":{"versions":["3.1.4"],"state":"fixed"},"advisories":[],"risk":0.0442},"relatedVulnerabilities":[{"id":"CVE-2024-34064","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34064","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb","https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS/","https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb","https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS/"],"description":"Jinja is an extensible templating engine. The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for CVE-2024-22195 only addressed spaces but not other characters. Accepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe. This vulnerability is fixed in 3.1.4.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34064","epss":0.00085,"percentile":0.25888,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.2"}},"found":{"versionConstraint":"<3.1.4 (python)","vulnerabilityID":"GHSA-h75v-3vvj-5mfj"},"fix":{"suggestedVersion":"3.1.4"}}],"artifact":{"id":"9ee154135ba244b0","name":"jinja2","version":"3.1.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-gmj6-6f8f-6699","dataSource":"https://github.com/advisories/GHSA-gmj6-6f8f-6699","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through malicious filenames","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.044160000000000005},"relatedVulnerabilities":[{"id":"CVE-2024-56201","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56201","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/767b23617628419ae3709ccfb02f9602ae9fe51f","https://github.com/pallets/jinja/issues/1792","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-gmj6-6f8f-6699"],"description":"Jinja is an extensible templating engine. In versions on the 3.x branch prior to 3.1.5, a bug in the Jinja compiler allows an attacker that controls both the content and filename of a template to execute arbitrary Python code, regardless of if Jinja's sandbox is used. To exploit the vulnerability, an attacker needs to control both the filename and the contents of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates where the template author can also choose the template filename. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.2"}},"found":{"versionConstraint":">=3.0.0,<=3.1.4 (python)","vulnerabilityID":"GHSA-gmj6-6f8f-6699"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"9ee154135ba244b0","name":"jinja2","version":"3.1.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3219","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3219","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/2621a8a40ba4b2c68ca564671b7daa5da80a4508","https://github.com/python/cpython/commit/31302f5fc24eecd693f0c8aaba7c2840b09b594d","https://github.com/python/cpython/commit/3f5d9d12c74787fbf3f5891835c85cc15526c86d","https://github.com/python/cpython/commit/5df322e91a40909e6904bbdbc0c3a6b6a9eead39","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/78df1043dbdce5c989600616f9f87b4ee72944e5","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/commit/c21a36112a0028d7ac3cf8f480e0dc88dba5922c","https://github.com/python/cpython/commit/c5655aa6ad120d2ed7f255bebd6e8b71a9c07dde","https://github.com/python/cpython/commit/e319f774f9e766a2b92949444a2d46081df3363a","https://github.com/python/cpython/commit/f071f01b7b7e19d7d6b3a4b0ec62f820ecb14660","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","https://security.netapp.com/advisory/ntap-20250502-0004/"],"description":"The\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.1},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3219","epss":0.00059,"percentile":0.18705,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc1"],"state":"fixed"},"advisories":[],"risk":0.029795000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-3219","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.5"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-9287","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-9287","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7","https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db","https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8","https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97","https://github.com/python/cpython/commit/d48cc82ed25e26b02eb97c6263d95dcaa1e9111b","https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483","https://github.com/python/cpython/issues/124651","https://github.com/python/cpython/pull/124712","https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/","https://security.netapp.com/advisory/ntap-20250425-0006/"],"description":"A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:Green","metrics":{"baseScore":5.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-9287","epss":0.00038,"percentile":0.10564,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1","3.14.0a2"],"state":"fixed"},"advisories":[],"risk":0.026695},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-9287","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.11,>= 3.12.0, < 3.12.8,>= 3.13.0, < 3.13.1,>= 3.14.0a1, < 3.14.0a2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.8"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3220","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3220","namespace":"nvd:cpe","severity":"Low","urls":["https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/","http://www.openwall.com/lists/oss-security/2025/02/14/8","https://security.netapp.com/advisory/ntap-20250314-0001/"],"description":"There is a defect in the CPython standard library module “mimetypes” where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as “/etc/mime.types”) also being used on Windows, where they are user-writable locations (“C:\\etc\\mime.types”).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (“[]”) on Windows platforms to avoid using the default list of known file locations.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3220","epss":0.00088,"percentile":0.26555,"date":"2025-06-02"}],"fix":{"versions":["3.14.0"],"state":"fixed"},"advisories":[],"risk":0.023320000000000004},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-3220","versionConstraint":"< 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-c33w-24p9-8m24","dataSource":"https://github.com/advisories/GHSA-c33w-24p9-8m24","namespace":"github:language:python","severity":"Low","urls":[],"description":"configobj ReDoS exploitable by developer using values in a server-side configuration file","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":3.7,"exploitabilityScore":2.3,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-26112","epss":0.00066,"percentile":0.20812,"date":"2025-06-02"}],"fix":{"versions":["5.0.9"],"state":"fixed"},"advisories":[],"risk":0.022109999999999998},"relatedVulnerabilities":[{"id":"CVE-2023-26112","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-26112","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/DiffSK/configobj/issues/232","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BO4RLMYEJODCNUE3DJIIUUFVTPAG6VN/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NZHY7B33EFY4LESP2NI4APQUPRROTAZK/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYU4IHVLOTYMFPH7KDOJGKZQR4GKWPFK/","https://security.snyk.io/vuln/SNYK-PYTHON-CONFIGOBJ-3252494","https://github.com/DiffSK/configobj/issues/232","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BO4RLMYEJODCNUE3DJIIUUFVTPAG6VN/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NZHY7B33EFY4LESP2NI4APQUPRROTAZK/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYU4IHVLOTYMFPH7KDOJGKZQR4GKWPFK/","https://security.snyk.io/vuln/SNYK-PYTHON-CONFIGOBJ-3252494"],"description":"All versions of the package configobj are vulnerable to Regular Expression Denial of Service (ReDoS) via the validate function, using (.+?)\\((.*)\\).\r\r**Note:** This is only exploitable in the case of a developer, putting the offending value in a server side configuration file.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"report@snyk.io","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":3.7,"exploitabilityScore":2.3,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-26112","epss":0.00066,"percentile":0.20812,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"configobj","version":"5.0.8"}},"found":{"versionConstraint":"<5.0.9 (python)","vulnerabilityID":"GHSA-c33w-24p9-8m24"},"fix":{"suggestedVersion":"5.0.9"}}],"artifact":{"id":"0381d295853b8f20","name":"configobj","version":"5.0.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/configobj-5.0.8.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/configobj-5.0.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/configobj-5.0.8.dist-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/configobj-5.0.8.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD (2 clause)"],"cpes":["cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers)_project:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers)_project:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers)project:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers)project:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers)_project:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers):python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers):python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers)project:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rob_dennis,_eli_courtwright_(michael_foord_&_nicola_larosa_original_maintainers):configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobj_project:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobj_project:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobjproject:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobjproject:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobj_project:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobj:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobj:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobjproject:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python-configobj:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python-configobj:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python_configobj:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python_configobj:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:rdennis+configobj:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:configobj:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:configobj:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python-configobj:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python_configobj:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python-configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python_configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:configobj:configobj:5.0.8:*:*:*:*:*:*:*","cpe:2.3:a:python:configobj:5.0.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/configobj@5.0.8","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-50602","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-50602","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/libexpat/libexpat/pull/915","https://lists.debian.org/debian-lts-announce/2025/04/msg00040.html","https://security.netapp.com/advisory/ntap-20250404-0008/"],"description":"An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-50602","epss":0.00037,"percentile":0.10035,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1"],"state":"fixed"},"advisories":[],"risk":0.020165000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-50602","versionConstraint":"< 3.9.21,>= 3.10, < 3.10.16,>= 3.11, < 3.11.11,>= 3.12, < 3.12.8,>= 3.13, < 3.13.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.8"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-cpwx-vrp4-4pq7","dataSource":"https://github.com/advisories/GHSA-cpwx-vrp4-4pq7","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja2 vulnerable to sandbox breakout through attr filter selecting format method","cvss":[],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}],"fix":{"versions":["3.1.6"],"state":"fixed"},"advisories":[],"risk":0.017},"relatedVulnerabilities":[{"id":"CVE-2025-27516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-27516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/90457bbf33b8662926ae65cdde4c4c32e756e403","https://github.com/pallets/jinja/security/advisories/GHSA-cpwx-vrp4-4pq7","https://lists.debian.org/debian-lts-announce/2025/04/msg00045.html"],"description":"Jinja is an extensible templating engine. Prior to 3.1.6, an oversight in how the Jinja sandboxed environment interacts with the |attr filter allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to use the |attr filter to get a reference to a string's plain format method, bypassing the sandbox. After the fix, the |attr filter no longer bypasses the environment's attribute lookup. This vulnerability is fixed in 3.1.6.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.2"}},"found":{"versionConstraint":"<=3.1.5 (python)","vulnerabilityID":"GHSA-cpwx-vrp4-4pq7"},"fix":{"suggestedVersion":"3.1.6"}}],"artifact":{"id":"9ee154135ba244b0","name":"jinja2","version":"3.1.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/Jinja2-3.1.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08074,"date":"2025-06-02"}],"fix":{"versions":["2.2.2"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08074,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"2.0.7"}},"found":{"versionConstraint":">=2.0.0,<2.2.2 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"2.2.2"}}],"artifact":{"id":"325b0c6757a3164f","name":"urllib3","version":"2.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-2.0.7.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/urllib3-2.0.7.dist-info/METADATA","annotations":{"evidence":"primary"}}],"language":"python","licenses":[],"cpes":["cpe:2.3:a:python:urllib3:2.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@2.0.7","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4030","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4030","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/","https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/"],"description":"On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.\n\nIf you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.\n\nThis issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":7.1,"exploitabilityScore":1.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4030","epss":0.00014,"percentile":0.0153,"date":"2025-06-02"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0b1"],"state":"fixed"},"advisories":[],"risk":0.01022},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2024-4030","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0b1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.4"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142","https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e","https://github.com/python/cpython/issues/133767","https://github.com/python/cpython/pull/129648","https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/","http://www.openwall.com/lists/oss-security/2025/05/16/4","http://www.openwall.com/lists/oss-security/2025/05/19/1"],"description":"There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:H/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4516","epss":0.00018,"percentile":0.03232,"date":"2025-06-02"}],"fix":{"versions":["3.14.0b1"],"state":"fixed"},"advisories":[],"risk":0.009810000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.3"}},"found":{"vulnerabilityID":"CVE-2025-4516","versionConstraint":"< 3.14.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0b1"}}],"artifact":{"id":"45a074cb15717c5e","name":"python","version":"3.12.3","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.3:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.0055,"date":"2025-06-02"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.0055,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.31.0"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"f6260eb9ac94b978","name":"requests","version":"2.31.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/requests-2.31.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/requests-2.31.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/requests-2.31.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/requests-2.31.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.31.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.31.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-h4gh-qq45-vh27","dataSource":"https://github.com/advisories/GHSA-h4gh-qq45-vh27","namespace":"github:language:python","severity":"Medium","urls":[],"description":"pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["43.0.1"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":">=37.0.0,<43.0.1 (python)","vulnerabilityID":"GHSA-h4gh-qq45-vh27"},"fix":{"suggestedVersion":"43.0.1"}}],"artifact":{"id":"4fb75bcf5cd65cf7","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-41.0.7.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-h4gh-qq45-vh27","dataSource":"https://github.com/advisories/GHSA-h4gh-qq45-vh27","namespace":"github:language:python","severity":"Medium","urls":[],"description":"pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["43.0.1"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.7"}},"found":{"versionConstraint":">=37.0.0,<43.0.1 (python)","vulnerabilityID":"GHSA-h4gh-qq45-vh27"},"fix":{"suggestedVersion":"43.0.1"}}],"artifact":{"id":"10851c6f62cd71db","name":"cryptography","version":"41.0.7","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.7:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.7","upstreams":[]}}],"source":{"type":"sbom-file","target":"core24-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/core24-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/core24-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T13:02:34.382621+01:00"}}
