{"matches":[{"vulnerability":{"id":"CVE-2025-0938","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-0938","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/526617ed68cde460236c973e5d0a8bad4de896ba","https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403","https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568","https://github.com/python/cpython/commit/b8b4b713c5f8ec0958c7ef8d29d6711889bc94ab","https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a","https://github.com/python/cpython/commit/ff4e5c25666f63544071a6b075ae8b25c98b7a32","https://github.com/python/cpython/issues/105704","https://github.com/python/cpython/pull/129418","https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/","https://security.netapp.com/advisory/ntap-20250314-0002/"],"description":"The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-0938","epss":0.01039,"percentile":0.76355,"date":"2025-06-04"}],"fix":{"versions":["3.9.22","3.10.17","3.11.12","3.12.9","3.13.2","3.14.0a5"],"state":"fixed"},"advisories":[],"risk":0.5870349999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2025-0938","versionConstraint":"< 3.9.22,>= 3.10.0, < 3.10.17,>= 3.11.0, < 3.11.12,>= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.9"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-12254","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-12254","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/71e8429ac8e2adc10084ab5ec29a62f4b6671a82","https://github.com/python/cpython/commit/9aa0deb2eef2655a1029ba228527b152353135b5","https://github.com/python/cpython/commit/e991ac8f2037d78140e417cc9a9486223eb3e786","https://github.com/python/cpython/issues/127655","https://github.com/python/cpython/pull/127656","https://mail.python.org/archives/list/security-announce@python.org/thread/H4O3UBAOAQQXGT4RE3E4XQYR5XLROORB/","http://www.openwall.com/lists/oss-security/2024/12/06/1","https://security.netapp.com/advisory/ntap-20250404-0010/"],"description":"Starting in Python 3.12.0, the asyncio._SelectorSocketTransport.writelines()\n method would not \"pause\" writing and signal to the Protocol to drain \nthe buffer to the wire once the write buffer reached the \"high-water \nmark\". Because of this, Protocols would not periodically drain the write\n buffer potentially leading to memory exhaustion.\n\n\n\n\n\nThis\n vulnerability likely impacts a small number of users, you must be using\n Python 3.12.0 or later, on macOS or Linux, using the asyncio module \nwith protocols, and using .writelines() method which had new \nzero-copy-on-write behavior in Python 3.12.0 and later. If not all of \nthese factors are true then your usage of Python is unaffected.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":8.7},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-12254","epss":0.00144,"percentile":0.35852,"date":"2025-06-04"}],"fix":{"versions":["3.12.9","3.13.2","3.14.0a3"],"state":"fixed"},"advisories":[],"risk":0.11232000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2024-12254","versionConstraint":">= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a3 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.9"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4138","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4138","namespace":"nvd:cpe","severity":"High","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4138","epss":0.00091,"percentile":0.27007,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.06824999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2025-4138","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.11"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4517","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4517","namespace":"nvd:cpe","severity":"Critical","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L","metrics":{"baseScore":9.4,"exploitabilityScore":3.9,"impactScore":5.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4517","epss":0.00072,"percentile":0.22754,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.06624000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2025-4517","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.11"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4330","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4330","namespace":"nvd:cpe","severity":"High","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4330","epss":0.00059,"percentile":0.188,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.044250000000000005},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2025-4330","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.11"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4435","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4435","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"When using a TarFile.errorlevel = 0 and extracting with a filter the documented behavior is that any filtered members would be skipped and not extracted. However the actual behavior of TarFile.errorlevel = 0 in affected versions is that the member would still be extracted and not skipped.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4435","epss":0.00045,"percentile":0.13345,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.03375},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2025-4435","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.11"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-9287","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-9287","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7","https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db","https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8","https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97","https://github.com/python/cpython/commit/d48cc82ed25e26b02eb97c6263d95dcaa1e9111b","https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483","https://github.com/python/cpython/issues/124651","https://github.com/python/cpython/pull/124712","https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/","https://security.netapp.com/advisory/ntap-20250425-0006/"],"description":"A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:Green","metrics":{"baseScore":5.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-9287","epss":0.00038,"percentile":0.10514,"date":"2025-06-04"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1","3.14.0a2"],"state":"fixed"},"advisories":[],"risk":0.026695},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2024-9287","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.11,>= 3.12.0, < 3.12.8,>= 3.13.0, < 3.13.1,>= 3.14.0a1, < 3.14.0a2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.8"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-12718","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-12718","namespace":"nvd:cpe","severity":"Medium","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/127987","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-12718","epss":0.00048,"percentile":0.14668,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.02472},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2024-12718","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.11"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3220","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3220","namespace":"nvd:cpe","severity":"Low","urls":["https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/","http://www.openwall.com/lists/oss-security/2025/02/14/8","https://security.netapp.com/advisory/ntap-20250314-0001/"],"description":"There is a defect in the CPython standard library module “mimetypes” where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as “/etc/mime.types”) also being used on Windows, where they are user-writable locations (“C:\\etc\\mime.types”).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (“[]”) on Windows platforms to avoid using the default list of known file locations.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3220","epss":0.00088,"percentile":0.26479,"date":"2025-06-04"}],"fix":{"versions":["3.14.0"],"state":"fixed"},"advisories":[],"risk":0.023320000000000004},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2024-3220","versionConstraint":"< 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-50602","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-50602","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/libexpat/libexpat/pull/915","https://lists.debian.org/debian-lts-announce/2025/04/msg00040.html","https://security.netapp.com/advisory/ntap-20250404-0008/"],"description":"An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-50602","epss":0.00037,"percentile":0.09978,"date":"2025-06-04"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1"],"state":"fixed"},"advisories":[],"risk":0.020165000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2024-50602","versionConstraint":"< 3.9.21,>= 3.10, < 3.10.16,>= 3.11, < 3.11.11,>= 3.12, < 3.12.8,>= 3.13, < 3.13.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.12.8"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/4398b788ffc1f954a2c552da285477d42a571292","https://github.com/python/cpython/commit/6279eb8c076d89d3739a6edb393e43c7929b429d","https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142","https://github.com/python/cpython/commit/73b3040f592436385007918887b7e2132aa8431f","https://github.com/python/cpython/commit/8d35fd1b34935221aff23a1ab69a429dd156be77","https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e","https://github.com/python/cpython/commit/ab9893c40609935e0d40a6d2a7307ea51aec598b","https://github.com/python/cpython/issues/133767","https://github.com/python/cpython/pull/129648","https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/","http://www.openwall.com/lists/oss-security/2025/05/16/4","http://www.openwall.com/lists/oss-security/2025/05/19/1"],"description":"There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:H/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4516","epss":0.00019,"percentile":0.03228,"date":"2025-06-04"}],"fix":{"versions":["3.14.0b1"],"state":"fixed"},"advisories":[],"risk":0.010355000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.12.6"}},"found":{"vulnerabilityID":"CVE-2025-4516","versionConstraint":"< 3.14.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0b1"}}],"artifact":{"id":"6601bf0d7d7107c2","name":"python","version":"3.12.6","type":"binary","locations":[{"path":"/usr/bin/python3.12","accessPath":"/usr/bin/python3.12","annotations":{"evidence":"primary"}},{"path":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","accessPath":"/usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.12.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.12.6:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.12.6","upstreams":[]}}],"source":{"type":"sbom-file","target":"bombsquad-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-05/bombsquad-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-05/bombsquad-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-05T01:31:25Z_1749096706.tar.zst?checksum=sha256%3A24dc57a0b7d2706052872f420ddca5abab34b90decaee92a89332592c849a2a5","built":"2025-06-05T04:11:46Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-05T01:32:09Z","input":"xxh64:780c2c656ce1d818"},"amazon":{"captured":"2025-06-05T01:32:19Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-05T01:32:23Z","input":"xxh64:0c246d8283177ef7"},"debian":{"captured":"2025-06-05T01:31:25Z","input":"xxh64:72a4935fec4da89a"},"epss":{"captured":"2025-06-05T01:32:06Z","input":"xxh64:4c501d68557ccc97"},"github":{"captured":"2025-06-05T01:32:09Z","input":"xxh64:237f1457ca101f77"},"kev":{"captured":"2025-06-05T01:32:18Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-05T01:32:10Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-05T01:32:24Z","input":"xxh64:3a7bcfe94e16f829"},"oracle":{"captured":"2025-06-05T01:32:23Z","input":"xxh64:c163376f725963f7"},"rhel":{"captured":"2025-06-05T01:33:08Z","input":"xxh64:ed12499e5526e0bd"},"sles":{"captured":"2025-06-05T01:32:25Z","input":"xxh64:2cad5f74e7325d3e"},"ubuntu":{"captured":"2025-06-05T01:33:03Z","input":"xxh64:56531baa95d5b463"},"wolfi":{"captured":"2025-06-05T01:32:09Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-05T06:41:19.327759+01:00"}}
