{"matches":[{"vulnerability":{"id":"CVE-2007-4559","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2007-4559","namespace":"nvd:cpe","severity":"Medium","urls":["http://mail.python.org/pipermail/python-dev/2007-August/074290.html","http://mail.python.org/pipermail/python-dev/2007-August/074292.html","http://secunia.com/advisories/26623","http://www.vupen.com/english/advisories/2007/3022","https://bugzilla.redhat.com/show_bug.cgi?id=263261","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CVBB7NU3YIRRDOKLYVN647WPRR3IAKR6/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FI55PGL47ES3OU2FQPGEHOI2EK3S2OBH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KA4Z44ZAI4SY7THCFBUDNT5EEFO4XQ3A/","https://security.gentoo.org/glsa/202309-06","http://mail.python.org/pipermail/python-dev/2007-August/074290.html","http://mail.python.org/pipermail/python-dev/2007-August/074292.html","http://secunia.com/advisories/26623","http://www.vupen.com/english/advisories/2007/3022","https://bugzilla.redhat.com/show_bug.cgi?id=263261","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CVBB7NU3YIRRDOKLYVN647WPRR3IAKR6/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FI55PGL47ES3OU2FQPGEHOI2EK3S2OBH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KA4Z44ZAI4SY7THCFBUDNT5EEFO4XQ3A/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CVBB7NU3YIRRDOKLYVN647WPRR3IAKR6/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FI55PGL47ES3OU2FQPGEHOI2EK3S2OBH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KA4Z44ZAI4SY7THCFBUDNT5EEFO4XQ3A/","https://security.gentoo.org/glsa/202309-06"],"description":"Directory traversal vulnerability in the (1) extract and (2) extractall functions in the tarfile module in Python allows user-assisted remote attackers to overwrite arbitrary files via a .. (dot dot) sequence in filenames in a TAR archive, a related issue to CVE-2001-1267.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:P/I:P/A:P","metrics":{"baseScore":6.8,"exploitabilityScore":8.6,"impactScore":6.5},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2007-4559","epss":0.9302,"percentile":0.99769,"date":"2025-06-04"}],"fix":{"versions":["3.6.16","3.8.17","3.9.17","3.10.12","3.11.4"],"state":"fixed"},"advisories":[],"risk":61.858300000000014},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2007-4559","versionConstraint":"< 3.6.16,>= 3.10.0, < 3.10.12,>= 3.11.0, < 3.11.4,>= 3.7.0, < 3.8.17,>= 3.9.0, < 3.9.17 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.16"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-48565","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-48565","namespace":"nvd:cpe","severity":"Critical","urls":["https://bugs.python.org/issue42051","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AFHYAGWBFBNUGWU6XWKBHTCV5NH77MB7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BAYWJD576JUKLHCWKDLMJSUGTRDKPF3M/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KZRZRJHWLZ7MOJNPQBWGJVXMVYDC5BRA/","https://security.netapp.com/advisory/ntap-20231006-0007/","https://bugs.python.org/issue42051","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AFHYAGWBFBNUGWU6XWKBHTCV5NH77MB7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BAYWJD576JUKLHCWKDLMJSUGTRDKPF3M/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KZRZRJHWLZ7MOJNPQBWGJVXMVYDC5BRA/","https://security.netapp.com/advisory/ntap-20231006-0007/"],"description":"An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-48565","epss":0.0412,"percentile":0.88057,"date":"2025-06-04"}],"fix":{"versions":["3.6.13","3.7.10","3.8.7","3.9.1"],"state":"fixed"},"advisories":[],"risk":3.8728000000000007},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-48565","versionConstraint":"< 3.6.13,>= 3.7.0, < 3.7.10,>= 3.8.0, < 3.8.7,>= 3.9.0, < 3.9.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.13"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-24329","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-24329","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/issues/102153","https://github.com/python/cpython/pull/99421","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/","https://pointernull.com/security/python-url-parse-problem.html","https://security.netapp.com/advisory/ntap-20230324-0004/","https://www.kb.cert.org/vuls/id/127587","https://github.com/python/cpython/issues/102153","https://github.com/python/cpython/pull/99421","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/","https://pointernull.com/security/python-url-parse-problem.html","https://security.netapp.com/advisory/ntap-20230324-0004/","https://www.kb.cert.org/vuls/id/127587"],"description":"An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-24329","epss":0.0105,"percentile":0.76488,"date":"2025-06-04"}],"fix":{"versions":["3.7.17","3.8.17","3.9.17","3.10.12","3.11.4"],"state":"fixed"},"advisories":[],"risk":0.7875},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2023-24329","versionConstraint":"< 3.7.17,>= 3.10.0, < 3.10.12,>= 3.11.0, < 3.11.4,>= 3.8.0, < 3.8.17,>= 3.9.0, < 3.9.17 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.7.17"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2019-9674","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-9674","namespace":"nvd:cpe","severity":"High","urls":["http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html","http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html","https://bugs.python.org/issue36260","https://bugs.python.org/issue36462","https://github.com/python/cpython/blob/master/Lib/zipfile.py","https://python-security.readthedocs.io/security.html#archives-and-zip-bomb","https://security.netapp.com/advisory/ntap-20200221-0003/","https://usn.ubuntu.com/4428-1/","https://www.python.org/news/security/","http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html","http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html","https://bugs.python.org/issue36260","https://bugs.python.org/issue36462","https://github.com/python/cpython/blob/master/Lib/zipfile.py","https://python-security.readthedocs.io/security.html#archives-and-zip-bomb","https://security.netapp.com/advisory/ntap-20200221-0003/","https://usn.ubuntu.com/4428-1/","https://www.python.org/news/security/"],"description":"Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-9674","epss":0.01138,"percentile":0.77365,"date":"2025-06-04"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.7823749999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2019-9674","versionConstraint":"<= 3.7.2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-6232","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6232","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/34ddb64d088dd7ccc321f6103d23153256caa5d4","https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06","https://github.com/python/cpython/commit/743acbe872485dc18df4d8ab2dc7895187f062c4","https://github.com/python/cpython/commit/7d1f50cd92ff7e10a1c15a8f591dde8a6843a64d","https://github.com/python/cpython/commit/b4225ca91547aa97ed3aca391614afbb255bc877","https://github.com/python/cpython/commit/d449caf8a179e3b954268b3a88eb9170be3c8fbf","https://github.com/python/cpython/commit/ed3a49ea734ada357ff4442996fd4ae71d253373","https://github.com/python/cpython/issues/121285","https://github.com/python/cpython/pull/121286","https://mail.python.org/archives/list/security-announce@python.org/thread/JRYFTPRHZRTLMZLWQEUHZSJXNHM4ACTY/","http://www.openwall.com/lists/oss-security/2024/09/03/5","https://security.netapp.com/advisory/ntap-20241018-0007/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\n\n\n\n\nRegular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6232","epss":0.00834,"percentile":0.73499,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.6255000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-6232","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-555c-2p6r-68mm","dataSource":"https://github.com/advisories/GHSA-555c-2p6r-68mm","namespace":"github:language:dotnet","severity":"High","urls":[],"description":".NET Denial of Service vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-29331","epss":0.00802,"percentile":0.72988,"date":"2025-06-04"}],"fix":{"versions":["6.0.6"],"state":"fixed"},"advisories":[],"risk":0.6014999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-29331","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-29331","namespace":"nvd:cpe","severity":"High","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-29331","https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-29331"],"description":".NET, .NET Framework, and Visual Studio Denial of Service Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-29331","epss":0.00802,"percentile":0.72988,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"Microsoft.Windows.Compatibility","version":"6.0.0"}},"found":{"versionConstraint":">=6.0.0,<=6.0.4 (unknown)","vulnerabilityID":"GHSA-555c-2p6r-68mm"},"fix":{"suggestedVersion":"6.0.6"}}],"artifact":{"id":"286ec7badf97a682","name":"Microsoft.Windows.Compatibility","version":"6.0.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:microsoft_windows_compatibility:microsoft_windows_compatibility_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_windows_compatibility:microsoft_windows_compatibility:6.0.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/Microsoft.Windows.Compatibility@6.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-555c-2p6r-68mm","dataSource":"https://github.com/advisories/GHSA-555c-2p6r-68mm","namespace":"github:language:dotnet","severity":"High","urls":[],"description":".NET Denial of Service vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-29331","epss":0.00802,"percentile":0.72988,"date":"2025-06-04"}],"fix":{"versions":["6.0.3"],"state":"fixed"},"advisories":[],"risk":0.6014999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-29331","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-29331","namespace":"nvd:cpe","severity":"High","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-29331","https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-29331"],"description":".NET, .NET Framework, and Visual Studio Denial of Service Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-29331","epss":0.00802,"percentile":0.72988,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"System.Security.Cryptography.Pkcs","version":"6.0.0"}},"found":{"versionConstraint":">=6.0.0,<=6.0.2 (unknown)","vulnerabilityID":"GHSA-555c-2p6r-68mm"},"fix":{"suggestedVersion":"6.0.3"}}],"artifact":{"id":"51caa59d46b0aee2","name":"System.Security.Cryptography.Pkcs","version":"6.0.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/System.Security.Cryptography.Pkcs.dll","accessPath":"/app/resources/dotnet/System.Security.Cryptography.Pkcs.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:system_security_cryptography_pkcs:system_security_cryptography_pkcs_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:system_security_cryptography_pkcs:system_security_cryptography_pkcs:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_security_cryptography_pkcs_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_security_cryptography_pkcs:6.0.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/System.Security.Cryptography.Pkcs@6.0.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-26488","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-26488","namespace":"nvd:cpe","severity":"High","urls":["https://mail.python.org/archives/list/security-announce%40python.org/thread/657Z4XULWZNIY5FRP3OWXHYKUSIH6DMN/","https://security.netapp.com/advisory/ntap-20220419-0005/","https://mail.python.org/archives/list/security-announce%40python.org/thread/657Z4XULWZNIY5FRP3OWXHYKUSIH6DMN/","https://security.netapp.com/advisory/ntap-20220419-0005/"],"description":"In Python before 3.10.3 on Windows, local users can gain privileges because the search path is inadequately secured. The installer may allow a local attacker to add user-writable directories to the system search path. To exploit, an administrator must have installed Python for all users and enabled PATH entries. A non-administrative user can trigger a repair that incorrectly adds user-writable paths into PATH, enabling search-path hijacking of other users and system services. This affects Python (CPython) through 3.7.12, 3.8.x through 3.8.12, 3.9.x through 3.9.10, and 3.10.x through 3.10.2.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7,"exploitabilityScore":1.1,"impactScore":5.9},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:L/AC:M/Au:N/C:P/I:P/A:P","metrics":{"baseScore":4.4,"exploitabilityScore":3.4,"impactScore":6.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-26488","epss":0.0089,"percentile":0.74428,"date":"2025-06-04"}],"fix":{"versions":["3.7.13","3.8.13","3.9.11","3.10.3","3.11.0b1"],"state":"fixed"},"advisories":[],"risk":0.5874},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-26488","versionConstraint":"< 3.7.13,>= 3.10.0a0, < 3.10.3,>= 3.11.0a0, < 3.11.0b1,>= 3.8.0a0, < 3.8.13,>= 3.9.0a0, < 3.9.11 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.7.13"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-0938","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-0938","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/526617ed68cde460236c973e5d0a8bad4de896ba","https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403","https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568","https://github.com/python/cpython/commit/b8b4b713c5f8ec0958c7ef8d29d6711889bc94ab","https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a","https://github.com/python/cpython/commit/ff4e5c25666f63544071a6b075ae8b25c98b7a32","https://github.com/python/cpython/issues/105704","https://github.com/python/cpython/pull/129418","https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/","https://security.netapp.com/advisory/ntap-20250314-0002/"],"description":"The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-0938","epss":0.01039,"percentile":0.76355,"date":"2025-06-04"}],"fix":{"versions":["3.9.22","3.10.17","3.11.12","3.12.9","3.13.2","3.14.0a5"],"state":"fixed"},"advisories":[],"risk":0.5870349999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-0938","versionConstraint":"< 3.9.22,>= 3.10.0, < 3.10.17,>= 3.11.0, < 3.11.12,>= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.22"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq66-vcfc-8246","dataSource":"https://github.com/advisories/GHSA-mq66-vcfc-8246","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Mercurial Path Traversal/Link Following vulnerability","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-3902","epss":0.00996,"percentile":0.75861,"date":"2025-06-04"}],"fix":{"versions":["4.9"],"state":"fixed"},"advisories":[],"risk":0.54282},"relatedVulnerabilities":[{"id":"CVE-2019-3902","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-3902","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3902","https://lists.debian.org/debian-lts-announce/2019/04/msg00024.html","https://lists.debian.org/debian-lts-announce/2020/07/msg00032.html","https://usn.ubuntu.com/4086-1/","https://www.mercurial-scm.org/wiki/WhatsNew#Mercurial_4.9_.282019-02-01.29","https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3902","https://lists.debian.org/debian-lts-announce/2019/04/msg00024.html","https://lists.debian.org/debian-lts-announce/2020/07/msg00032.html","https://usn.ubuntu.com/4086-1/","https://www.mercurial-scm.org/wiki/WhatsNew#Mercurial_4.9_.282019-02-01.29"],"description":"A flaw was found in Mercurial before 4.9. It was possible to use symlinks and subrepositories to defeat Mercurial's path-checking logic and write files outside a repository.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:N/I:P/A:P","metrics":{"baseScore":5.8,"exploitabilityScore":8.6,"impactScore":5},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.1,"exploitabilityScore":1.5,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-3902","epss":0.00996,"percentile":0.75861,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"mercurial","version":"4.8.2"}},"found":{"versionConstraint":"<4.9 (python)","vulnerabilityID":"GHSA-mq66-vcfc-8246"},"fix":{"suggestedVersion":"4.9"}}],"artifact":{"id":"7f9b95b11ec67fa2","name":"mercurial","version":"4.8.2","type":"python","locations":[{"path":"/usr/lib/python2.7/dist-packages/mercurial-4.8.2.egg-info","accessPath":"/usr/lib/python2.7/dist-packages/mercurial-4.8.2.egg-info","annotations":{"evidence":"primary"}}],"language":"python","licenses":["GNU GPLv2 or any later version"],"cpes":["cpe:2.3:a:matt_mackall_and_many_others_project:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_others_project:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_othersproject:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_othersproject:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_others_project:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_others:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_others:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_othersproject:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:matt_mackall_and_many_others:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurial_project:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurial_project:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurialproject:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurialproject:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python-mercurial:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python-mercurial:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python_mercurial:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python_mercurial:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurial_project:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurial:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurial:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurialproject:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python-mercurial:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python_mercurial:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:mercurial:mercurial:4.8.2:*:*:*:*:*:*:*","cpe:2.3:a:python:mercurial:4.8.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/mercurial@4.8.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-f32c-w444-8ppv","dataSource":"https://github.com/advisories/GHSA-f32c-w444-8ppv","namespace":"github:language:dotnet","severity":"High","urls":[],"description":"Microsoft Security Advisory CVE-2024-43484 | .NET Denial of Service Vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-43484","epss":0.0067,"percentile":0.70239,"date":"2025-06-04"}],"fix":{"versions":["6.0.1"],"state":"fixed"},"advisories":[],"risk":0.5025},"relatedVulnerabilities":[{"id":"CVE-2024-43484","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-43484","namespace":"nvd:cpe","severity":"High","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-43484","https://security.netapp.com/advisory/ntap-20250328-0007/"],"description":".NET, .NET Framework, and Visual Studio Denial of Service Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-43484","epss":0.0067,"percentile":0.70239,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"System.IO.Packaging","version":"6.0.0"}},"found":{"versionConstraint":">=6.0.0-preview.1.21102.12,<=6.0.0 (unknown)","vulnerabilityID":"GHSA-f32c-w444-8ppv"},"fix":{"suggestedVersion":"6.0.1"}}],"artifact":{"id":"773f6aafd8ea057b","name":"System.IO.Packaging","version":"6.0.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/System.IO.Packaging.dll","accessPath":"/app/resources/dotnet/System.IO.Packaging.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:microsoft_corporation:system_io_packaging_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:system_io_packaging:system_io_packaging_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_io_packaging:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:system_io_packaging:system_io_packaging:6.0.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/System.IO.Packaging@6.0.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2017-17522","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2017-17522","namespace":"nvd:cpe","severity":"High","urls":["http://www.securityfocus.com/bid/102207","https://bugs.python.org/issue32367","https://security-tracker.debian.org/tracker/CVE-2017-17522","http://www.securityfocus.com/bid/102207","https://bugs.python.org/issue32367","https://security-tracker.debian.org/tracker/CVE-2017-17522"],"description":"Lib/webbrowser.py in Python through 3.6.3 does not validate strings before launching the program specified by the BROWSER environment variable, which might allow remote attackers to conduct argument-injection attacks via a crafted URL. NOTE: a software maintainer indicates that exploitation is impossible because the code relies on subprocess.Popen and the default shell=False setting","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:P/I:P/A:P","metrics":{"baseScore":6.8,"exploitabilityScore":8.6,"impactScore":6.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2017-17522","epss":0.00584,"percentile":0.67909,"date":"2025-06-04"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.44675999999999993},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2017-17522","versionConstraint":"<= 3.6.3 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-0391","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-0391","namespace":"nvd:cpe","severity":"High","urls":["https://bugs.python.org/issue43882","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/","https://security.gentoo.org/glsa/202305-02","https://security.netapp.com/advisory/ntap-20220225-0009/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://bugs.python.org/issue43882","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/","https://security.gentoo.org/glsa/202305-02","https://security.netapp.com/advisory/ntap-20220225-0009/","https://www.oracle.com/security-alerts/cpuapr2022.html"],"description":"A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:P/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-0391","epss":0.00631,"percentile":0.69232,"date":"2025-06-04"}],"fix":{"versions":["3.6.14","3.7.11","3.8.11","3.9.5"],"state":"fixed"},"advisories":[],"risk":0.4338125},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-0391","versionConstraint":"< 3.6.14,>= 3.7.0, < 3.7.11,>= 3.8.0, < 3.8.11,>= 3.9.0, < 3.9.5,= 3.10.0-alpha1,= 3.10.0-alpha2,= 3.10.0-alpha3,= 3.10.0-alpha4,= 3.10.0-alpha5,= 3.10.0-alpha6 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.14"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4032","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4032","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml","http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"],"description":"The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4032","epss":0.00526,"percentile":0.65989,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0a6"],"state":"fixed"},"advisories":[],"risk":0.39449999999999996},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-4032","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0a6,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-vh55-786g-wjwj","dataSource":"https://github.com/advisories/GHSA-vh55-786g-wjwj","namespace":"github:language:dotnet","severity":"Medium","urls":[],"description":".NET Information Disclosure Vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-34716","epss":0.00704,"percentile":0.70975,"date":"2025-06-04"}],"fix":{"versions":["6.0.1"],"state":"fixed"},"advisories":[],"risk":0.38368},"relatedVulnerabilities":[{"id":"CVE-2022-34716","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-34716","namespace":"nvd:cpe","severity":"Medium","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-34716","https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-34716"],"description":".NET Spoofing Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-34716","epss":0.00704,"percentile":0.70975,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"System.Security.Cryptography.Xml","version":"6.0.0"}},"found":{"versionConstraint":">=5.0.0,<=6.0.0 (unknown)","vulnerabilityID":"GHSA-vh55-786g-wjwj"},"fix":{"suggestedVersion":"6.0.1"}}],"artifact":{"id":"16a45287855e03bd","name":"System.Security.Cryptography.Xml","version":"6.0.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/System.Security.Cryptography.Xml.dll","accessPath":"/app/resources/dotnet/System.Security.Cryptography.Xml.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:system_security_cryptography_xml:system_security_cryptography_xml_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:system_security_cryptography_xml:system_security_cryptography_xml:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_security_cryptography_xml_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_security_cryptography_xml:6.0.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/System.Security.Cryptography.Xml@6.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-qj66-m88j-hmgj","dataSource":"https://github.com/advisories/GHSA-qj66-m88j-hmgj","namespace":"github:language:dotnet","severity":"High","urls":[],"description":"Microsoft Security Advisory CVE-2024-43483 | .NET Denial of Service Vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-43483","epss":0.00401,"percentile":0.59847,"date":"2025-06-04"}],"fix":{"versions":["6.0.1"],"state":"fixed"},"advisories":[],"risk":0.30074999999999996},"relatedVulnerabilities":[{"id":"CVE-2024-43483","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-43483","namespace":"nvd:cpe","severity":"High","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-43483"],"description":".NET, .NET Framework, and Visual Studio Denial of Service Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-43483","epss":0.00401,"percentile":0.59847,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"System.IO.Packaging","version":"6.0.0"}},"found":{"versionConstraint":">=6.0.0-preview.1.21102.12,<=6.0.0 (unknown)","vulnerabilityID":"GHSA-qj66-m88j-hmgj"},"fix":{"suggestedVersion":"6.0.1"}}],"artifact":{"id":"773f6aafd8ea057b","name":"System.IO.Packaging","version":"6.0.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/System.IO.Packaging.dll","accessPath":"/app/resources/dotnet/System.IO.Packaging.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:microsoft_corporation:system_io_packaging_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:system_io_packaging:system_io_packaging_.net:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_io_packaging:6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:system_io_packaging:system_io_packaging:6.0.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/System.IO.Packaging@6.0.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-0397","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0397","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/2","https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d","https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524","https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e","https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286","https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa","https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab","https://github.com/python/cpython/issues/114572","https://github.com/python/cpython/pull/114573","https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/","http://www.openwall.com/lists/oss-security/2024/06/17/2","https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d","https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524","https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e","https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286","https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa","https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab","https://github.com/python/cpython/issues/114572","https://github.com/python/cpython/pull/114573","https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/","https://security.netapp.com/advisory/ntap-20250411-0006/"],"description":"A defect was discovered in the Python “ssl” module where there is a memory\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\n“get_ca_certs()”. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0397","epss":0.00393,"percentile":0.59417,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.14","3.11.9","3.12.3","3.13.0a5"],"state":"fixed"},"advisories":[],"risk":0.292785},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-0397","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.9,>= 3.12.0, < 3.12.3,>= 3.13.0a1, < 3.13.0a5,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-98g6-xh36-x2p7","dataSource":"https://github.com/advisories/GHSA-98g6-xh36-x2p7","namespace":"github:language:dotnet","severity":"High","urls":[],"description":"Microsoft.Data.SqlClient and System.Data.SqlClient vulnerable to SQL Data Provider Security Feature Bypass","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N","metrics":{"baseScore":8.7,"exploitabilityScore":2.3,"impactScore":5.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0056","epss":0.00356,"percentile":0.57087,"date":"2025-06-04"}],"fix":{"versions":["4.8.6"],"state":"fixed"},"advisories":[],"risk":0.28835999999999995},"relatedVulnerabilities":[{"id":"CVE-2024-0056","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0056","namespace":"nvd:cpe","severity":"High","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-0056","https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-0056"],"description":"Microsoft.Data.SqlClient and System.Data.SqlClient SQL Data Provider Security Feature Bypass Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N","metrics":{"baseScore":8.7,"exploitabilityScore":2.3,"impactScore":5.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0056","epss":0.00356,"percentile":0.57087,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"System.Data.SqlClient","version":"4.8.3"}},"found":{"versionConstraint":"<4.8.6 (unknown)","vulnerabilityID":"GHSA-98g6-xh36-x2p7"},"fix":{"suggestedVersion":"4.8.6"}}],"artifact":{"id":"4eafc623ac24082c","name":"System.Data.SqlClient","version":"4.8.3","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/System.Data.SqlClient.dll","accessPath":"/app/resources/dotnet/System.Data.SqlClient.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:microsoft_corporation:system_data_sqlclient_.net:4.8.3:*:*:*:*:*:*:*","cpe:2.3:a:system_data_sqlclient:system_data_sqlclient_.net:4.8.3:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_data_sqlclient:4.8.3:*:*:*:*:*:*:*","cpe:2.3:a:system_data_sqlclient:system_data_sqlclient:4.8.3:*:*:*:*:*:*:*"],"purl":"pkg:nuget/System.Data.SqlClient@4.8.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-5642","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-5642","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/06/28/4","https://github.com/python/cpython/commit/39258d3595300bc7b952854c915f63ae2d4b9c3e","https://github.com/python/cpython/issues/121227","https://github.com/python/cpython/pull/23014","https://jbp.io/2024/06/27/cve-2024-5535-openssl-memory-safety.html","https://mail.python.org/archives/list/security-announce@python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/","https://security.netapp.com/advisory/ntap-20240726-0005/","http://www.openwall.com/lists/oss-security/2024/06/28/4","https://github.com/python/cpython/commit/39258d3595300bc7b952854c915f63ae2d4b9c3e","https://github.com/python/cpython/issues/121227","https://github.com/python/cpython/pull/23014","https://jbp.io/2024/06/27/cve-2024-5535-openssl-memory-safety.html","https://mail.python.org/archives/list/security-announce@python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/","https://security.netapp.com/advisory/ntap-20240726-0005/"],"description":"CPython 3.9 and earlier doesn't disallow configuring an empty list (\"[]\") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5642","epss":0.00486,"percentile":0.64296,"date":"2025-06-04"}],"fix":{"versions":["3.10.0b1"],"state":"fixed"},"advisories":[],"risk":0.27945},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-5642","versionConstraint":"< 3.10.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.0b1"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2021-3733","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3733","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugs.python.org/issue43075","https://bugzilla.redhat.com/show_bug.cgi?id=1995234","https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb","https://github.com/python/cpython/pull/24391","https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html","https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html","https://security.netapp.com/advisory/ntap-20220407-0001/","https://ubuntu.com/security/CVE-2021-3733","https://bugs.python.org/issue43075","https://bugzilla.redhat.com/show_bug.cgi?id=1995234","https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb","https://github.com/python/cpython/pull/24391","https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html","https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html","https://security.netapp.com/advisory/ntap-20220407-0001/","https://ubuntu.com/security/CVE-2021-3733"],"description":"There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.5,"exploitabilityScore":2.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:S/C:N/I:N/A:P","metrics":{"baseScore":4,"exploitabilityScore":8,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3733","epss":0.00439,"percentile":0.62146,"date":"2025-06-04"}],"fix":{"versions":["3.6.14","3.7.11","3.8.10","3.9.5"],"state":"fixed"},"advisories":[],"risk":0.22498749999999998},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2021-3733","versionConstraint":"< 3.6.14,>= 3.7.0, < 3.7.11,>= 3.8.0, < 3.8.10,>= 3.9.0, < 3.9.5,= 3.10.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.14"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-xhg6-9j5j-w4vf","dataSource":"https://github.com/advisories/GHSA-xhg6-9j5j-w4vf","namespace":"github:language:dotnet","severity":"High","urls":[],"description":"DotNetZip Directory Traversal vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-48510","epss":0.00256,"percentile":0.49012,"date":"2025-06-04"}],"fix":{"versions":[],"state":"not-fixed"},"advisories":[],"risk":0.22144},"relatedVulnerabilities":[{"id":"CVE-2024-48510","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-48510","namespace":"nvd:cpe","severity":"Critical","urls":["https://gist.github.com/thomas-chauchefoin-bentley-systems/855218959116f870f08857cce2aec731","https://github.com/haf/DotNetZip.Semverd","https://github.com/haf/DotNetZip.Semverd/blob/e487179b33a9a0f2631eed5fb04d2c952ea5377a/src/Zip.Shared/ZipEntry.Extract.cs#L1365-L1410","https://www.nuget.org/packages/DotNetZip/"],"description":"Directory Traversal vulnerability in DotNetZip v.1.16.0 and before allows a remote attacker to execute arbitrary code via the src/Zip.Shared/ZipEntry.Extract.cs component NOTE: This vulnerability only affects products that are no longer supported by the maintainer.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-48510","epss":0.00256,"percentile":0.49012,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"DotNetZip","version":"1.16.0"}},"found":{"versionConstraint":">=1.10.1,<=1.16.0 (unknown)","vulnerabilityID":"GHSA-xhg6-9j5j-w4vf"}}],"artifact":{"id":"83e5ab9254e83afa","name":"DotNetZip","version":"1.16.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/DotNetZip.dll","accessPath":"/app/resources/dotnet/DotNetZip.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:dotnetzip:dotnetzip_.net:1.16.0:*:*:*:*:*:*:*","cpe:2.3:a:dotnetzip:dotnetzip:1.16.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/DotNetZip@1.16.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-7592","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-7592","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/391e5626e3ee5af267b97e37abc7475732e67621","https://github.com/python/cpython/commit/44e458357fca05ca0ae2658d62c8c595b048b5ef","https://github.com/python/cpython/commit/a77ab24427a18bff817025adb03ca920dc3f1a06","https://github.com/python/cpython/commit/b2f11ca7667e4d57c71c1c88b255115f16042d9a","https://github.com/python/cpython/commit/d4ac921a4b081f7f996a5d2b101684b67ba0ed7f","https://github.com/python/cpython/commit/d662e2db2605515a767f88ad48096b8ac623c774","https://github.com/python/cpython/commit/dcc3eaef98cd94d6cb6cb0f44bd1c903d04f33b1","https://github.com/python/cpython/issues/123067","https://github.com/python/cpython/pull/123075","https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/","https://security.netapp.com/advisory/ntap-20241018-0006/"],"description":"There is a LOW severity vulnerability affecting CPython, specifically the\n'http.cookies' standard library module.\n\n\nWhen parsing cookies that contained backslashes for quoted characters in\nthe cookie value, the parser would use an algorithm with quadratic\ncomplexity, resulting in excess CPU resources being used while parsing the\nvalue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-7592","epss":0.00255,"percentile":0.48881,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.19125},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-7592","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2021-23336","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-23336","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2021/02/19/4","http://www.openwall.com/lists/oss-security/2021/05/01/2","https://github.com/python/cpython/pull/24297","https://lists.apache.org/thread.html/ra8ce70088ba291f358e077cafdb14d174b7a1ce9a9d86d1b332d6367%40%3Cusers.airflow.apache.org%3E","https://lists.apache.org/thread.html/rc005f4de9d9b0ba943ceb8ff5a21a5c6ff8a9df52632476698d99432%40%3Cannounce.apache.org%3E","https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772%40%3Cdev.mina.apache.org%3E","https://lists.debian.org/debian-lts-announce/2021/02/msg00030.html","https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html","https://lists.debian.org/debian-lts-announce/2021/04/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3EPYWWFDV22CJ5AOH5VCE72DOASZZ255/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3YKKDLXL3UEZ3J426C2XTBS63AHE46SM/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/46N6A52EGSXHJYCZWVMBJJIH4NWIV2B5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FONHJIOZOFD7CD35KZL6SVBUTMBPGZGA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HCQTCSP6SCVIYNIRUJC5X7YBVUHPLSC4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HZTM7KLHFCE3LWSEVO2NAFLUHMGYMCRY/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IHQDU7NXA7EWAE4W7VO6MURVJIULEPPR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KJXCMHLY7H3FIYLE4OKDYUILU2CCRUCZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LVNH6Z24IG3E67ZCQGGJ46FZB4XFLQNZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MNUN5SOMFL2BBKP6ZAICIIUPQKZDMGYO/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MP572OLHMS7MZO4KUPSCIMSZIA5IZZ62/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NJSCSN722JO2E2AGPWD4NTGVELVRPB4R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NODWHDIFBQE5RU5PUWUVE47JOT5VCMJ2/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OAGSWNGZJ6HQ5ISA67SNMK3CJRKICET7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RSLQD5CCM75IZGAMBDGUZEATYU5YSGJ7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGIY6I4YS3WOXAK4SXKIEOC2G4VZKIR7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TFTELUMWZE3KV3JB2H5EE6VFRZFRD5MV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/W2LSKBEFI5SYEY5FM6ICZVZM5WRQUCS4/","https://security.gentoo.org/glsa/202104-04","https://security.netapp.com/advisory/ntap-20210326-0004/","https://snyk.io/blog/cache-poisoning-in-popular-open-source-packages/","https://snyk.io/vuln/SNYK-UPSTREAM-PYTHONCPYTHON-1074933","https://www.oracle.com//security-alerts/cpujul2021.html","https://www.oracle.com/security-alerts/cpuApr2021.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html","http://www.openwall.com/lists/oss-security/2021/02/19/4","http://www.openwall.com/lists/oss-security/2021/05/01/2","https://github.com/python/cpython/pull/24297","https://lists.apache.org/thread.html/ra8ce70088ba291f358e077cafdb14d174b7a1ce9a9d86d1b332d6367%40%3Cusers.airflow.apache.org%3E","https://lists.apache.org/thread.html/rc005f4de9d9b0ba943ceb8ff5a21a5c6ff8a9df52632476698d99432%40%3Cannounce.apache.org%3E","https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772%40%3Cdev.mina.apache.org%3E","https://lists.debian.org/debian-lts-announce/2021/02/msg00030.html","https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html","https://lists.debian.org/debian-lts-announce/2021/04/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3EPYWWFDV22CJ5AOH5VCE72DOASZZ255/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3YKKDLXL3UEZ3J426C2XTBS63AHE46SM/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/46N6A52EGSXHJYCZWVMBJJIH4NWIV2B5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FONHJIOZOFD7CD35KZL6SVBUTMBPGZGA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HCQTCSP6SCVIYNIRUJC5X7YBVUHPLSC4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HZTM7KLHFCE3LWSEVO2NAFLUHMGYMCRY/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IHQDU7NXA7EWAE4W7VO6MURVJIULEPPR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KJXCMHLY7H3FIYLE4OKDYUILU2CCRUCZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LVNH6Z24IG3E67ZCQGGJ46FZB4XFLQNZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MNUN5SOMFL2BBKP6ZAICIIUPQKZDMGYO/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MP572OLHMS7MZO4KUPSCIMSZIA5IZZ62/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NJSCSN722JO2E2AGPWD4NTGVELVRPB4R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NODWHDIFBQE5RU5PUWUVE47JOT5VCMJ2/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OAGSWNGZJ6HQ5ISA67SNMK3CJRKICET7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RSLQD5CCM75IZGAMBDGUZEATYU5YSGJ7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGIY6I4YS3WOXAK4SXKIEOC2G4VZKIR7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TFTELUMWZE3KV3JB2H5EE6VFRZFRD5MV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/W2LSKBEFI5SYEY5FM6ICZVZM5WRQUCS4/","https://security.gentoo.org/glsa/202104-04","https://security.netapp.com/advisory/ntap-20210326-0004/","https://snyk.io/blog/cache-poisoning-in-popular-open-source-packages/","https://snyk.io/vuln/SNYK-UPSTREAM-PYTHONCPYTHON-1074933","https://www.oracle.com//security-alerts/cpujul2021.html","https://www.oracle.com/security-alerts/cpuApr2021.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"The package python/cpython from 0 and before 3.6.13, from 3.7.0 and before 3.7.10, from 3.8.0 and before 3.8.8, from 3.9.0 and before 3.9.2 are vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":1.7,"impactScore":4.3},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:H/Au:N/C:N/I:P/A:P","metrics":{"baseScore":4,"exploitabilityScore":5,"impactScore":5},"vendorMetadata":{}},{"source":"report@snyk.io","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":1.7,"impactScore":4.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-23336","epss":0.00326,"percentile":0.54896,"date":"2025-06-04"}],"fix":{"versions":["3.6.13","3.7.10","3.8.8","3.9.2"],"state":"fixed"},"advisories":[],"risk":0.16734666666666664},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2021-23336","versionConstraint":"< 3.6.13,>= 3.7.0, < 3.7.10,>= 3.8.0, < 3.8.8,>= 3.9.0, < 3.9.2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.13"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-40217","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-40217","namespace":"nvd:cpe","severity":"Medium","urls":["https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/","https://security.netapp.com/advisory/ntap-20231006-0014/","https://www.python.org/dev/security/","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/","https://security.netapp.com/advisory/ntap-20231006-0014/","https://www.python.org/dev/security/"],"description":"An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-40217","epss":0.00284,"percentile":0.51534,"date":"2025-06-04"}],"fix":{"versions":["3.8.18","3.9.18","3.10.13","3.11.5"],"state":"fixed"},"advisories":[],"risk":0.14626},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2023-40217","versionConstraint":"< 3.8.18,>= 3.10.0, < 3.10.13,>= 3.11.0, < 3.11.5,>= 3.9.0, < 3.9.18 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.18"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-48560","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-48560","namespace":"nvd:cpe","severity":"High","urls":["https://bugs.python.org/issue39421","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZ5OOBWNYWXFTZDMCGHJVGDLDTHLWITJ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VO7Y2YZSDK3UYJD2KBGLXRTGNG6T326J/","https://security.netapp.com/advisory/ntap-20230929-0008/","https://bugs.python.org/issue39421","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZ5OOBWNYWXFTZDMCGHJVGDLDTHLWITJ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VO7Y2YZSDK3UYJD2KBGLXRTGNG6T326J/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JZ5OOBWNYWXFTZDMCGHJVGDLDTHLWITJ/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VO7Y2YZSDK3UYJD2KBGLXRTGNG6T326J/","https://security.netapp.com/advisory/ntap-20230929-0008/"],"description":"A use-after-free exists in Python through 3.9 via heappushpop in heapq.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-48560","epss":0.00173,"percentile":0.39504,"date":"2025-06-04"}],"fix":{"versions":["3.6.11","3.7.7","3.8.2"],"state":"fixed"},"advisories":[],"risk":0.12975},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-48560","versionConstraint":"< 3.6.11,>= 3.7.0, < 3.7.7,>= 3.8.0, < 3.8.2,= 3.9.0-alpha1,= 3.9.0-alpha2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.11"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2015-5652","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2015-5652","namespace":"nvd:cpe","severity":"High","urls":["http://jvn.jp/en/jp/JVN49503705/995204/index.html","http://jvn.jp/en/jp/JVN49503705/index.html","http://jvndb.jvn.jp/jvndb/JVNDB-2015-000141","http://www.securityfocus.com/bid/76929","https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05324755","http://jvn.jp/en/jp/JVN49503705/995204/index.html","http://jvn.jp/en/jp/JVN49503705/index.html","http://jvndb.jvn.jp/jvndb/JVNDB-2015-000141","http://www.securityfocus.com/bid/76929","https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05324755"],"description":"Untrusted search path vulnerability in python.exe in Python through 3.5.0 on Windows allows local users to gain privileges via a Trojan horse readline.pyd file in the current working directory.  NOTE: the vendor says \"It was determined that this is a longtime behavior of Python that cannot really be altered at this point.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:L/AC:L/Au:N/C:C/I:C/A:C","metrics":{"baseScore":7.2,"exploitabilityScore":4,"impactScore":10.1},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2015-5652","epss":0.0015,"percentile":0.36681,"date":"2025-06-04"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.11025},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2015-5652","versionConstraint":"<= 3.5.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-0450","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0450","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/30fe5d853b56138dbec62432d370a1f99409fc85","https://github.com/python/cpython/commit/66363b9a7b9fe7c99eba3a185b74c5fdbf842eba","https://github.com/python/cpython/commit/70497218351ba44bffc8b571201ecb5652d84675","https://github.com/python/cpython/commit/a2c59992e9e8d35baba9695eb186ad6c6ff85c51","https://github.com/python/cpython/commit/a956e510f6336d5ae111ba429a61c3ade30a7549","https://github.com/python/cpython/commit/d05bac0b74153beb541b88b4fca33bf053990183","https://github.com/python/cpython/commit/fa181fcf2156f703347b03a3b1966ce47be8ab3b","https://github.com/python/cpython/issues/109858","https://lists.debian.org/debian-lts-announce/2024/03/msg00024.html","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/XELNUX2L3IOHBTFU7RQHCY6OUVEWZ2FG/","https://www.bamsoftware.com/hacks/zipbomb/","http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/30fe5d853b56138dbec62432d370a1f99409fc85","https://github.com/python/cpython/commit/66363b9a7b9fe7c99eba3a185b74c5fdbf842eba","https://github.com/python/cpython/commit/70497218351ba44bffc8b571201ecb5652d84675","https://github.com/python/cpython/commit/a2c59992e9e8d35baba9695eb186ad6c6ff85c51","https://github.com/python/cpython/commit/a956e510f6336d5ae111ba429a61c3ade30a7549","https://github.com/python/cpython/commit/d05bac0b74153beb541b88b4fca33bf053990183","https://github.com/python/cpython/commit/fa181fcf2156f703347b03a3b1966ce47be8ab3b","https://github.com/python/cpython/issues/109858","https://lists.debian.org/debian-lts-announce/2024/03/msg00024.html","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/XELNUX2L3IOHBTFU7RQHCY6OUVEWZ2FG/","https://security.netapp.com/advisory/ntap-20250411-0005/","https://www.bamsoftware.com/hacks/zipbomb/"],"description":"An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0450","epss":0.00173,"percentile":0.39489,"date":"2025-06-04"}],"fix":{"versions":["3.8.19","3.9.19","3.10.14","3.11.8","3.12.2","3.13.0a3"],"state":"fixed"},"advisories":[],"risk":0.09688000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-0450","versionConstraint":"< 3.8.19,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.8,>= 3.12.0, < 3.12.2,>= 3.13.0a1, < 3.13.0a3,>= 3.9.0, < 3.9.19 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.19"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2017-18207","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2017-18207","namespace":"nvd:cpe","severity":"Medium","urls":["http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html","https://bugs.python.org/issue32056","http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html","https://bugs.python.org/issue32056"],"description":"The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \"need to be prepared to handle a wide variety of exceptions.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.5,"exploitabilityScore":2.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:N/I:N/A:P","metrics":{"baseScore":4.3,"exploitabilityScore":8.6,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2017-18207","epss":0.0016,"percentile":0.37896,"date":"2025-06-04"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.08320000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2017-18207","versionConstraint":"<= 3.6.4 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-11168","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-11168","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/29f348e232e82938ba2165843c448c2b291504c5","https://github.com/python/cpython/commit/634ded45545ce8cbd6fd5d49785613dd7fa9b89e","https://github.com/python/cpython/commit/b2171a2fd41416cf68afd67460578631d755a550","https://github.com/python/cpython/commit/ddca2953191c67a12b1f19d6bca41016c6ae7132","https://github.com/python/cpython/issues/103848","https://github.com/python/cpython/pull/103849","https://mail.python.org/archives/list/security-announce@python.org/thread/XPWB6XVZ5G5KGEI63M4AWLIEUF5BPH4T/","https://security.netapp.com/advisory/ntap-20250411-0004/"],"description":"The urllib.parse.urlsplit() and urlparse() functions improperly validated bracketed hosts (`[]`), allowing hosts that weren't IPv6 or IPvFuture. This behavior was not conformant to RFC 3986 and potentially enabled SSRF if a URL is processed by more than one URL parser.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:N/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.7,"exploitabilityScore":2.3,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-11168","epss":0.00154,"percentile":0.3722,"date":"2025-06-04"}],"fix":{"versions":["3.9.21","3.10.16","3.11.4","3.12.0b1"],"state":"fixed"},"advisories":[],"risk":0.077},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-11168","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.4,>= 3.12.0a1, < 3.12.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.21"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4138","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4138","namespace":"nvd:cpe","severity":"High","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4138","epss":0.00091,"percentile":0.27007,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.06824999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-4138","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.23"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4517","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4517","namespace":"nvd:cpe","severity":"Critical","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L","metrics":{"baseScore":9.4,"exploitabilityScore":3.9,"impactScore":5.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4517","epss":0.00072,"percentile":0.22754,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.06624000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-4517","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.23"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-45061","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-45061","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/issues/98433","https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html","https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2AOUKI72ACV6CHY2QUFO6VK2DNMVJ2MB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/35YDIWCUMWTMDBWFRAVENFH6BLB65D6S/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4WBZJNSALFGMPYTINIF57HAAK46U72WQ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/63FS6VHY4DCS74HBTEINUDOECQ2X6ZCH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7WQPHKGNXUJC3TC3BDW5RKGROWRJVSFR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B3YI6JYARWU6GULWOHNUROSACT54XFFS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4MYQ3IV6NWA4CKSXEHW45CH2YNDHEPH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BWJREJHWVRBYDP43YB5WRL3QC7UBA7BR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GTPVDZDATRQFE6KAT6B4BQIQ4GRHIIIJ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IN26PWZTYG6IF3APLRXQJBVACQHZUPT2/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JCDJXNBHWXNYUTOEV4H2HCFSRKV3SYL3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JTYVESWVBPD57ZJC35G5722Q6TS37WSB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KNE4GMD45RGC2HWUAAIGTDHT5VJ2E4O4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LKWAMPURWUV3DCCT4J7VHRF4NT2CFVBR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O67LRHDTJWH544KXB6KY4HMHQLYDXFPK/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORVCQGJCCAVLN4DJDTWGREFCUWXKQRML/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PLQ2BNZVBBAQPV3SPRU24ZD37UYJJS7W/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QCKD4AFBHXIMHS64ZER2U7QRT33HNE7L/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RH57BNT4VQERGEJ5SXNXSVMDYP66YD4H/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RTN2OOLKYTG34DODUEJGT5MLC2PFGPBA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T3D5TX4TDJPXHXD2QICKTY3OCQC3JARP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UHVW73QZJMHA4MK7JBT7CXX7XSNYQEGF/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VCMDX6IFKLOA3NXUQEV524L5LHTPI2JI/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/X3EJ6J7PXVQOULBQZQGBXCXY6LFF6LZD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XXZJL3CNAFS5PAIR7K4RL62S3Y7THR7O/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YPNWZKXPKTNHS5FVMN7UQZ2UPCSEFJUK/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZB5YCMIRVX35RUB6XPOWKENCVCJEVDRK/","https://security.gentoo.org/glsa/202305-02","https://security.netapp.com/advisory/ntap-20221209-0007/","https://github.com/python/cpython/issues/98433","https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html","https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2AOUKI72ACV6CHY2QUFO6VK2DNMVJ2MB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/35YDIWCUMWTMDBWFRAVENFH6BLB65D6S/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4WBZJNSALFGMPYTINIF57HAAK46U72WQ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/63FS6VHY4DCS74HBTEINUDOECQ2X6ZCH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7WQPHKGNXUJC3TC3BDW5RKGROWRJVSFR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B3YI6JYARWU6GULWOHNUROSACT54XFFS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4MYQ3IV6NWA4CKSXEHW45CH2YNDHEPH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BWJREJHWVRBYDP43YB5WRL3QC7UBA7BR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GTPVDZDATRQFE6KAT6B4BQIQ4GRHIIIJ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IN26PWZTYG6IF3APLRXQJBVACQHZUPT2/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JCDJXNBHWXNYUTOEV4H2HCFSRKV3SYL3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JTYVESWVBPD57ZJC35G5722Q6TS37WSB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KNE4GMD45RGC2HWUAAIGTDHT5VJ2E4O4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LKWAMPURWUV3DCCT4J7VHRF4NT2CFVBR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O67LRHDTJWH544KXB6KY4HMHQLYDXFPK/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORVCQGJCCAVLN4DJDTWGREFCUWXKQRML/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PLQ2BNZVBBAQPV3SPRU24ZD37UYJJS7W/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QCKD4AFBHXIMHS64ZER2U7QRT33HNE7L/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RH57BNT4VQERGEJ5SXNXSVMDYP66YD4H/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RTN2OOLKYTG34DODUEJGT5MLC2PFGPBA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T3D5TX4TDJPXHXD2QICKTY3OCQC3JARP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UHVW73QZJMHA4MK7JBT7CXX7XSNYQEGF/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VCMDX6IFKLOA3NXUQEV524L5LHTPI2JI/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/X3EJ6J7PXVQOULBQZQGBXCXY6LFF6LZD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XXZJL3CNAFS5PAIR7K4RL62S3Y7THR7O/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YPNWZKXPKTNHS5FVMN7UQZ2UPCSEFJUK/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZB5YCMIRVX35RUB6XPOWKENCVCJEVDRK/","https://security.gentoo.org/glsa/202305-02","https://security.netapp.com/advisory/ntap-20221209-0007/"],"description":"An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-45061","epss":0.0008,"percentile":0.24592,"date":"2025-06-04"}],"fix":{"versions":["3.7.16","3.8.16","3.9.16","3.10.9","3.11.1","3.12.0a3"],"state":"fixed"},"advisories":[],"risk":0.060000000000000005},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-45061","versionConstraint":"< 3.7.16,>= 3.10.0a0, < 3.10.9,>= 3.11.0a0, < 3.11.1,>= 3.12.0a0, < 3.12.0a3,>= 3.8.0a0, < 3.8.16,>= 3.9.0a0, < 3.9.16 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.7.16"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-27043","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-27043","namespace":"nvd:cpe","severity":"Medium","urls":["http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/","http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/"],"description":"The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-27043","epss":0.00115,"percentile":0.31257,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0a1"],"state":"fixed"},"advisories":[],"risk":0.059225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2023-27043","versionConstraint":"< 3.8.20,>= 3.10.0a0, < 3.10.15,>= 3.11.0a0, < 3.11.10,>= 3.12.0a0, < 3.12.6,>= 3.13.0a0, < 3.13.0a1,>= 3.9.0a0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-8088","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-8088","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/0aa1ee22ab6e204e9d3d0e9dd63ea648ed691ef1","https://github.com/python/cpython/commit/2231286d78d328c2f575e0b05b16fe447d1656d6","https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e","https://github.com/python/cpython/commit/7bc367e464ce50b956dd232c1dfa1cad4e7fb814","https://github.com/python/cpython/commit/7e8883a3f04d308302361aeffc73e0e9837f19d4","https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64","https://github.com/python/cpython/commit/95b073bddefa6243effa08e131e297c0383e7f6a","https://github.com/python/cpython/commit/962055268ed4f2ca1d717bfc8b6385de50a23ab7","https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea","https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db","https://github.com/python/cpython/commit/fc0b8259e693caa8400fa8b6ac1e494e47ea7798","https://github.com/python/cpython/issues/122905","https://github.com/python/cpython/issues/123270","https://github.com/python/cpython/pull/122906","https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/","http://www.openwall.com/lists/oss-security/2024/08/22/1","http://www.openwall.com/lists/oss-security/2024/08/22/4","http://www.openwall.com/lists/oss-security/2024/08/23/1","http://www.openwall.com/lists/oss-security/2024/08/23/2","https://security.netapp.com/advisory/ntap-20241011-0010/"],"description":"There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:N/AU:N/R:U/V:X/RE:L/U:X","metrics":{"baseScore":8.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-8088","epss":0.00071,"percentile":0.2248,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.05750999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-8088","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-6597","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-6597","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a","https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25","https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5","https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d","https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82","https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b","https://github.com/python/cpython/issues/91133","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/","http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a","https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25","https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5","https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d","https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82","https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b","https://github.com/python/cpython/issues/91133","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/"],"description":"An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N","metrics":{"baseScore":7.8,"exploitabilityScore":1.5,"impactScore":5.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-6597","epss":0.00073,"percentile":0.2308,"date":"2025-06-04"}],"fix":{"versions":["3.8.19","3.9.19","3.10.14","3.11.8","3.12.1","3.13.0a3"],"state":"fixed"},"advisories":[],"risk":0.05584499999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2023-6597","versionConstraint":"< 3.8.19,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.8,>= 3.12.0, < 3.12.1,>= 3.13.0a1, < 3.13.0a3,>= 3.9.0, < 3.9.19 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.19"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-48564","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-48564","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugs.python.org/issue42103","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://security.netapp.com/advisory/ntap-20230929-0009/","https://bugs.python.org/issue42103","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://security.netapp.com/advisory/ntap-20230929-0009/"],"description":"read_ints in plistlib.py in Python through 3.9.1 is vulnerable to a potential DoS attack via CPU and RAM exhaustion when processing malformed Apple Property List files in binary format.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.5,"exploitabilityScore":2.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-48564","epss":0.00089,"percentile":0.26728,"date":"2025-06-04"}],"fix":{"versions":["3.6.13","3.7.10","3.8.7","3.9.1"],"state":"fixed"},"advisories":[],"risk":0.05117499999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-48564","versionConstraint":"< 3.6.13,>= 3.7.0, < 3.7.10,>= 3.8.0, < 3.8.7,>= 3.9.0, < 3.9.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.13"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-6923","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6923","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/06f28dc236708f72871c64d4bc4b4ea144c50147","https://github.com/python/cpython/commit/097633981879b3c9de9a1dd120d3aa585ecc2384","https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7","https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0","https://github.com/python/cpython/commit/b158a76ce094897c870fb6b3de62887b7ccc33f1","https://github.com/python/cpython/commit/f7be505d137a22528cb0fc004422c0081d5d90e6","https://github.com/python/cpython/commit/f7c0f09e69e950cf3c5ada9dbde93898eb975533","https://github.com/python/cpython/issues/121650","https://github.com/python/cpython/pull/122233","https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/","http://www.openwall.com/lists/oss-security/2024/08/01/3","http://www.openwall.com/lists/oss-security/2024/08/02/2","https://lists.debian.org/debian-lts-announce/2025/01/msg00005.html","https://security.netapp.com/advisory/ntap-20240926-0003/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":5.5,"exploitabilityScore":2.1,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6923","epss":0.00089,"percentile":0.2663,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.046725},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-6923","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-1795","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-1795","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/python/cpython/commit/09fab93c3d857496c0bd162797fab816c311ee48","https://github.com/python/cpython/commit/70754d21c288535e86070ca7a6e90dcb670b8593","https://github.com/python/cpython/commit/9148b77e0af91cdacaa7fe3dfac09635c3fe9a74","https://github.com/python/cpython/issues/100884","https://github.com/python/cpython/pull/100885","https://github.com/python/cpython/pull/119099","https://mail.python.org/archives/list/security-announce@python.org/thread/MB62IZMEC3UM6SGHP5LET5JX2Y7H4ZUR/"],"description":"During an address list folding when a separating comma ends up on a folded line and that line is to be unicode-encoded then the separator itself is also unicode-encoded. Expected behavior is that the separating comma remains a plan comma. This can result in the address header being misinterpreted by some mail servers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:L/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-1795","epss":0.00167,"percentile":0.38825,"date":"2025-06-04"}],"fix":{"versions":["3.11.9","3.12.3","3.13.0a5"],"state":"fixed"},"advisories":[],"risk":0.044255},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-1795","versionConstraint":"< 3.11.9,>= 3.12.0, < 3.12.3,>= 3.13.0a1, < 3.13.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.11.9"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4330","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4330","namespace":"nvd:cpe","severity":"High","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4330","epss":0.00059,"percentile":0.188,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.044250000000000005},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-4330","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.23"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-8g2p-5pqh-5jmc","dataSource":"https://github.com/advisories/GHSA-8g2p-5pqh-5jmc","namespace":"github:language:dotnet","severity":"Medium","urls":[],"description":".NET Information Disclosure Vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N","metrics":{"baseScore":5.8,"exploitabilityScore":1.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-41064","epss":0.00076,"percentile":0.23705,"date":"2025-06-04"}],"fix":{"versions":["4.8.5"],"state":"fixed"},"advisories":[],"risk":0.04104000000000001},"relatedVulnerabilities":[{"id":"CVE-2022-41064","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-41064","namespace":"nvd:cpe","severity":"Medium","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-41064","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2022-41064"],"description":".NET Framework Information Disclosure Vulnerability","cvss":[{"source":"secure@microsoft.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N","metrics":{"baseScore":5.8,"exploitabilityScore":1.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-41064","epss":0.00076,"percentile":0.23705,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"System.Data.SqlClient","version":"4.8.3"}},"found":{"versionConstraint":"<=4.8.4 (unknown)","vulnerabilityID":"GHSA-8g2p-5pqh-5jmc"},"fix":{"suggestedVersion":"4.8.5"}}],"artifact":{"id":"4eafc623ac24082c","name":"System.Data.SqlClient","version":"4.8.3","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/System.Data.SqlClient.dll","accessPath":"/app/resources/dotnet/System.Data.SqlClient.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:microsoft_corporation:system_data_sqlclient_.net:4.8.3:*:*:*:*:*:*:*","cpe:2.3:a:system_data_sqlclient:system_data_sqlclient_.net:4.8.3:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:system_data_sqlclient:4.8.3:*:*:*:*:*:*:*","cpe:2.3:a:system_data_sqlclient:system_data_sqlclient:4.8.3:*:*:*:*:*:*:*"],"purl":"pkg:nuget/System.Data.SqlClient@4.8.3","upstreams":[]}},{"vulnerability":{"id":"CVE-2021-3177","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3177","namespace":"nvd:cpe","severity":"Critical","urls":["https://bugs.python.org/issue42938","https://github.com/python/cpython/pull/24239","https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772%40%3Cdev.mina.apache.org%3E","https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html","https://lists.debian.org/debian-lts-announce/2022/02/msg00013.html","https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BRHOCQYX3QLDGDQGTWQAUUT2GGIZCZUO/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CCFZMVRQUKCBQIG5F2CBVADK63NFSE4A/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FONHJIOZOFD7CD35KZL6SVBUTMBPGZGA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FPE7SMXYUIWPOIZV4DQYXODRXMFX3C5E/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HCQTCSP6SCVIYNIRUJC5X7YBVUHPLSC4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MGSV6BJQLRQ6RKVUXK7JGU7TP4QFGQXC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MP572OLHMS7MZO4KUPSCIMSZIA5IZZ62/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NODWHDIFBQE5RU5PUWUVE47JOT5VCMJ2/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NQPARTLNSFQVMMQHPNBFOCOZOO3TMQNA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXSMBHES3ANXXS2RSO5G6Q24BR4B2PWK/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/V6XJAULOS5JVB2L67NCKKMJ5NTKZJBSD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Y4KSYYWMGAKOA2JVCQA422OINT6CKQ7O/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YDTZVGSXQ7HR7OCGSUHTRNTMBG43OMKU/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Z7GZV74KM72O2PEJN2C4XP3V5Q5MZUOO/","https://news.ycombinator.com/item?id=26185005","https://python-security.readthedocs.io/vuln/ctypes-buffer-overflow-pycarg_repr.html","https://security.gentoo.org/glsa/202101-18","https://security.netapp.com/advisory/ntap-20210226-0003/","https://www.oracle.com//security-alerts/cpujul2021.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html","https://bugs.python.org/issue42938","https://github.com/python/cpython/pull/24239","https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772%40%3Cdev.mina.apache.org%3E","https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html","https://lists.debian.org/debian-lts-announce/2022/02/msg00013.html","https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BRHOCQYX3QLDGDQGTWQAUUT2GGIZCZUO/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CCFZMVRQUKCBQIG5F2CBVADK63NFSE4A/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FONHJIOZOFD7CD35KZL6SVBUTMBPGZGA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FPE7SMXYUIWPOIZV4DQYXODRXMFX3C5E/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HCQTCSP6SCVIYNIRUJC5X7YBVUHPLSC4/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MGSV6BJQLRQ6RKVUXK7JGU7TP4QFGQXC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MP572OLHMS7MZO4KUPSCIMSZIA5IZZ62/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NODWHDIFBQE5RU5PUWUVE47JOT5VCMJ2/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NQPARTLNSFQVMMQHPNBFOCOZOO3TMQNA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXSMBHES3ANXXS2RSO5G6Q24BR4B2PWK/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/V6XJAULOS5JVB2L67NCKKMJ5NTKZJBSD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Y4KSYYWMGAKOA2JVCQA422OINT6CKQ7O/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YDTZVGSXQ7HR7OCGSUHTRNTMBG43OMKU/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Z7GZV74KM72O2PEJN2C4XP3V5Q5MZUOO/","https://news.ycombinator.com/item?id=26185005","https://python-security.readthedocs.io/vuln/ctypes-buffer-overflow-pycarg_repr.html","https://security.gentoo.org/glsa/202101-18","https://security.netapp.com/advisory/ntap-20210226-0003/","https://www.oracle.com//security-alerts/cpujul2021.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:P/A:P","metrics":{"baseScore":7.5,"exploitabilityScore":10,"impactScore":6.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3177","epss":0.00044,"percentile":0.12896,"date":"2025-06-04"}],"fix":{"versions":["3.6.13","3.7.10","3.8.8","3.9.2","3.10.0"],"state":"fixed"},"advisories":[],"risk":0.03883},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2021-3177","versionConstraint":"< 3.6.13,>= 3.10.0a0, < 3.10.0,>= 3.7.0a0, < 3.7.10,>= 3.8.0a0, < 3.8.8,>= 3.9.0a0, < 3.9.2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.13"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4435","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4435","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"When using a TarFile.errorlevel = 0 and extracting with a filter the documented behavior is that any filtered members would be skipped and not extracted. However the actual behavior of TarFile.errorlevel = 0 in affected versions is that the member would still be extracted and not skipped.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4435","epss":0.00045,"percentile":0.13345,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.03375},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-4435","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.23"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2022-48566","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-48566","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugs.python.org/issue40791","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://security.netapp.com/advisory/ntap-20231006-0013/","https://bugs.python.org/issue40791","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://security.netapp.com/advisory/ntap-20231006-0013/"],"description":"An issue was discovered in compare_digest in Lib/hmac.py in Python through 3.9.1. Constant-time-defeating optimisations were possible in the accumulator variable in hmac.compare_digest.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-48566","epss":0.00057,"percentile":0.17963,"date":"2025-06-04"}],"fix":{"versions":["3.6.13","3.7.10","3.8.7","3.9.1"],"state":"fixed"},"advisories":[],"risk":0.031065},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2022-48566","versionConstraint":"< 3.6.13,>= 3.7.0, < 3.7.10,>= 3.8.0, < 3.8.7,>= 3.9.0, < 3.9.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.6.13"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3219","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3219","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/2621a8a40ba4b2c68ca564671b7daa5da80a4508","https://github.com/python/cpython/commit/31302f5fc24eecd693f0c8aaba7c2840b09b594d","https://github.com/python/cpython/commit/3f5d9d12c74787fbf3f5891835c85cc15526c86d","https://github.com/python/cpython/commit/5df322e91a40909e6904bbdbc0c3a6b6a9eead39","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/78df1043dbdce5c989600616f9f87b4ee72944e5","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/commit/c21a36112a0028d7ac3cf8f480e0dc88dba5922c","https://github.com/python/cpython/commit/c5655aa6ad120d2ed7f255bebd6e8b71a9c07dde","https://github.com/python/cpython/commit/e319f774f9e766a2b92949444a2d46081df3363a","https://github.com/python/cpython/commit/f071f01b7b7e19d7d6b3a4b0ec62f820ecb14660","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","https://security.netapp.com/advisory/ntap-20250502-0004/"],"description":"The\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.1},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3219","epss":0.00059,"percentile":0.18675,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc1"],"state":"fixed"},"advisories":[],"risk":0.029795000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-3219","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-9287","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-9287","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7","https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db","https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8","https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97","https://github.com/python/cpython/commit/d48cc82ed25e26b02eb97c6263d95dcaa1e9111b","https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483","https://github.com/python/cpython/issues/124651","https://github.com/python/cpython/pull/124712","https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/","https://security.netapp.com/advisory/ntap-20250425-0006/"],"description":"A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:Green","metrics":{"baseScore":5.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-9287","epss":0.00038,"percentile":0.10514,"date":"2025-06-04"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1","3.14.0a2"],"state":"fixed"},"advisories":[],"risk":0.026695},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-9287","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.11,>= 3.12.0, < 3.12.8,>= 3.13.0, < 3.13.1,>= 3.14.0a1, < 3.14.0a2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.21"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-12718","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-12718","namespace":"nvd:cpe","severity":"Medium","urls":["https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f","https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da","https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9","https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a","https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e","https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a","https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a","https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01","https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1","https://github.com/python/cpython/issues/127987","https://github.com/python/cpython/issues/135034","https://github.com/python/cpython/pull/135037","https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"],"description":"Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-12718","epss":0.00048,"percentile":0.14668,"date":"2025-06-04"}],"fix":{"versions":["3.9.23","3.10.18","3.11.13","3.12.11","3.13.4","3.14.0"],"state":"fixed"},"advisories":[],"risk":0.02472},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-12718","versionConstraint":"< 3.9.23,>= 3.10.0, < 3.10.18,>= 3.11.0, < 3.11.13,>= 3.12.0, < 3.12.11,>= 3.13.0, < 3.13.4,>= 3.14.0a1, < 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.23"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3220","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3220","namespace":"nvd:cpe","severity":"Low","urls":["https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/","http://www.openwall.com/lists/oss-security/2025/02/14/8","https://security.netapp.com/advisory/ntap-20250314-0001/"],"description":"There is a defect in the CPython standard library module “mimetypes” where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as “/etc/mime.types”) also being used on Windows, where they are user-writable locations (“C:\\etc\\mime.types”).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (“[]”) on Windows platforms to avoid using the default list of known file locations.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3220","epss":0.00088,"percentile":0.26479,"date":"2025-06-04"}],"fix":{"versions":["3.14.0"],"state":"fixed"},"advisories":[],"risk":0.023320000000000004},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-3220","versionConstraint":"< 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-36632","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-36632","namespace":"nvd:cpe","severity":"High","urls":["https://docs.python.org/3/library/email.html","https://docs.python.org/3/library/email.utils.html","https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py","https://github.com/python/cpython/issues/103800","https://docs.python.org/3/library/email.html","https://docs.python.org/3/library/email.utils.html","https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py","https://github.com/python/cpython/issues/103800"],"description":"The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-36632","epss":0.0003,"percentile":0.07038,"date":"2025-06-04"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.0225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2023-36632","versionConstraint":"<= 3.11.4 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-50602","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-50602","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/libexpat/libexpat/pull/915","https://lists.debian.org/debian-lts-announce/2025/04/msg00040.html","https://security.netapp.com/advisory/ntap-20250404-0008/"],"description":"An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-50602","epss":0.00037,"percentile":0.09978,"date":"2025-06-04"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1"],"state":"fixed"},"advisories":[],"risk":0.020165000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-50602","versionConstraint":"< 3.9.21,>= 3.10, < 3.10.16,>= 3.11, < 3.11.11,>= 3.12, < 3.12.8,>= 3.13, < 3.13.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.9.21"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-h4j7-5rxr-p4wc","dataSource":"https://github.com/advisories/GHSA-h4j7-5rxr-p4wc","namespace":"github:language:dotnet","severity":"Low","urls":[],"description":"Microsoft.Build.Tasks.Core .NET Spoofing Vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8,"exploitabilityScore":2.1,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-26646","epss":0.00029,"percentile":0.06405,"date":"2025-06-04"}],"fix":{"versions":["16.11.6"],"state":"fixed"},"advisories":[],"risk":0.01595},"relatedVulnerabilities":[{"id":"CVE-2025-26646","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-26646","namespace":"nvd:cpe","severity":"High","urls":["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2025-26646"],"description":"External control of file name or path in .NET, Visual Studio, and Build Tools for Visual Studio allows an authorized attacker to perform spoofing over a network.","cvss":[{"source":"secure@microsoft.com","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8,"exploitabilityScore":2.1,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-26646","epss":0.00029,"percentile":0.06405,"date":"2025-06-04"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"dotnet-matcher","searchedBy":{"language":"dotnet","namespace":"github:language:dotnet","package":{"name":"Microsoft.Build.Tasks.Core","version":"16.5.0"}},"found":{"versionConstraint":">=16.0.461,<=16.11.0 (unknown)","vulnerabilityID":"GHSA-h4j7-5rxr-p4wc"},"fix":{"suggestedVersion":"16.11.6"}}],"artifact":{"id":"df6a9d47543533a5","name":"Microsoft.Build.Tasks.Core","version":"16.5.0","type":"dotnet","locations":[{"path":"/app/resources/dotnet/ParanextDataProvider.deps.json","accessPath":"/app/resources/dotnet/ParanextDataProvider.deps.json","annotations":{"evidence":"primary"}},{"path":"/app/resources/dotnet/Microsoft.Build.Tasks.Core.dll","accessPath":"/app/resources/dotnet/Microsoft.Build.Tasks.Core.dll","annotations":{"evidence":"supporting"}}],"language":"dotnet","licenses":[],"cpes":["cpe:2.3:a:microsoft_build_tasks_core:microsoft_build_tasks_core_.net:16.5.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_build_tasks_core:microsoft_build_tasks_core:16.5.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:microsoft_build_tasks_core_.net:16.5.0:*:*:*:*:*:*:*","cpe:2.3:a:microsoft_corporation:microsoft_build_tasks_core:16.5.0:*:*:*:*:*:*:*"],"purl":"pkg:nuget/Microsoft.Build.Tasks.Core@16.5.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/4398b788ffc1f954a2c552da285477d42a571292","https://github.com/python/cpython/commit/6279eb8c076d89d3739a6edb393e43c7929b429d","https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142","https://github.com/python/cpython/commit/73b3040f592436385007918887b7e2132aa8431f","https://github.com/python/cpython/commit/8d35fd1b34935221aff23a1ab69a429dd156be77","https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e","https://github.com/python/cpython/commit/ab9893c40609935e0d40a6d2a7307ea51aec598b","https://github.com/python/cpython/issues/133767","https://github.com/python/cpython/pull/129648","https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/","http://www.openwall.com/lists/oss-security/2025/05/16/4","http://www.openwall.com/lists/oss-security/2025/05/19/1"],"description":"There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:H/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4516","epss":0.00019,"percentile":0.03228,"date":"2025-06-04"}],"fix":{"versions":["3.14.0b1"],"state":"fixed"},"advisories":[],"risk":0.010355000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2025-4516","versionConstraint":"< 3.14.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0b1"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4030","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4030","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/","https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/"],"description":"On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.\n\nIf you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.\n\nThis issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":7.1,"exploitabilityScore":1.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4030","epss":0.00014,"percentile":0.01492,"date":"2025-06-04"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0b1"],"state":"fixed"},"advisories":[],"risk":0.01022},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"package":{"name":"python","version":"2.7.18"}},"found":{"vulnerabilityID":"CVE-2024-4030","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0b1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.8.20"}}],"artifact":{"id":"495d0e6a9a600210","name":"python","version":"2.7.18","type":"binary","locations":[{"path":"/usr/bin/python2.7","accessPath":"/usr/bin/python2.7","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:2.7.18:*:*:*:*:*:*:*","cpe:2.3:a:python:python:2.7.18:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@2.7.18","upstreams":[]}}],"source":{"type":"sbom-file","target":"paratext-10-studio-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-05/paratext-10-studio-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-05/paratext-10-studio-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-05T01:31:25Z_1749096706.tar.zst?checksum=sha256%3A24dc57a0b7d2706052872f420ddca5abab34b90decaee92a89332592c849a2a5","built":"2025-06-05T04:11:46Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-05T01:32:09Z","input":"xxh64:780c2c656ce1d818"},"amazon":{"captured":"2025-06-05T01:32:19Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-05T01:32:23Z","input":"xxh64:0c246d8283177ef7"},"debian":{"captured":"2025-06-05T01:31:25Z","input":"xxh64:72a4935fec4da89a"},"epss":{"captured":"2025-06-05T01:32:06Z","input":"xxh64:4c501d68557ccc97"},"github":{"captured":"2025-06-05T01:32:09Z","input":"xxh64:237f1457ca101f77"},"kev":{"captured":"2025-06-05T01:32:18Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-05T01:32:10Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-05T01:32:24Z","input":"xxh64:3a7bcfe94e16f829"},"oracle":{"captured":"2025-06-05T01:32:23Z","input":"xxh64:c163376f725963f7"},"rhel":{"captured":"2025-06-05T01:33:08Z","input":"xxh64:ed12499e5526e0bd"},"sles":{"captured":"2025-06-05T01:32:25Z","input":"xxh64:2cad5f74e7325d3e"},"ubuntu":{"captured":"2025-06-05T01:33:03Z","input":"xxh64:56531baa95d5b463"},"wolfi":{"captured":"2025-06-05T01:32:09Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-05T06:43:39.32085+01:00"}}
