{"matches":[{"vulnerability":{"id":"GHSA-248v-346w-9cwc","dataSource":"https://github.com/advisories/GHSA-248v-346w-9cwc","namespace":"github:language:python","severity":"Low","urls":[],"description":"Certifi removes GLOBALTRUST root certificate","cvss":[],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82507,"date":"2025-06-03"}],"fix":{"versions":["2024.7.4"],"state":"fixed"},"advisories":[],"risk":0.5783999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-39689","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://security.netapp.com/advisory/ntap-20241206-0001/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82507,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2023.7.22"}},"found":{"versionConstraint":">=2021.5.30,<2024.7.4 (python)","vulnerabilityID":"GHSA-248v-346w-9cwc"},"fix":{"suggestedVersion":"2024.7.4"}}],"artifact":{"id":"6347d608985efae3","name":"certifi","version":"2023.7.22","type":"python","locations":[{"path":"/lib/python3.10/site-packages/certifi-2023.7.22.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/certifi-2023.7.22.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/certifi-2023.7.22.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/certifi-2023.7.22.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/certifi-2023.7.22.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/certifi-2023.7.22.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2023.7.22:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2023.7.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.3"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"8dca804f066e3dc8","name":"cryptography","version":"41.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-v845-jxx5-vc9f","dataSource":"https://github.com/advisories/GHSA-v845-jxx5-vc9f","namespace":"github:language:python","severity":"High","urls":[],"description":"`Cookie` HTTP header isn't stripped on cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}],"fix":{"versions":["1.26.17"],"state":"fixed"},"advisories":[],"risk":0.37118},"relatedVulnerabilities":[{"id":"CVE-2023-43804","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://security.netapp.com/advisory/ntap-20241213-0007/","https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.16"}},"found":{"versionConstraint":"<1.26.17 (python)","vulnerabilityID":"GHSA-v845-jxx5-vc9f"},"fix":{"suggestedVersion":"1.26.17"}}],"artifact":{"id":"4c4a01f87de9f09d","name":"urllib3","version":"1.26.16","type":"python","locations":[{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.16:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.16","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"68.1.2"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"a606ddc92fb2947e","name":"setuptools","version":"68.1.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:68.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@68.1.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfhm-5ghh-2f97","dataSource":"https://github.com/advisories/GHSA-jfhm-5ghh-2f97","namespace":"github:language:python","severity":"Medium","urls":[],"description":"cryptography vulnerable to NULL-dereference when loading PKCS7 certificates","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63032,"date":"2025-06-03"}],"fix":{"versions":["41.0.6"],"state":"fixed"},"advisories":[],"risk":0.24906500000000004},"relatedVulnerabilities":[{"id":"CVE-2023-49083","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-49083","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/","https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63032,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.3"}},"found":{"versionConstraint":">=3.1,<41.0.6 (python)","vulnerabilityID":"GHSA-jfhm-5ghh-2f97"},"fix":{"suggestedVersion":"41.0.6"}}],"artifact":{"id":"8dca804f066e3dc8","name":"cryptography","version":"41.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"3.4"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"4466a53e819eb0c9","name":"idna","version":"3.4","type":"python","locations":[{"path":"/lib/python3.10/site-packages/idna-3.4.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/idna-3.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/idna-3.4.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/idna-3.4.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:kim_davies_<kim_project:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim_project:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim_project:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:3.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@3.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-6vqw-3v5j-54x4","dataSource":"https://github.com/advisories/GHSA-6vqw-3v5j-54x4","namespace":"github:language:python","severity":"High","urls":[],"description":"cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49156,"date":"2025-06-03"}],"fix":{"versions":["42.0.4"],"state":"fixed"},"advisories":[],"risk":0.19275},"relatedVulnerabilities":[{"id":"CVE-2024-26130","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-26130","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4","https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49156,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.3"}},"found":{"versionConstraint":">=38.0.0,<42.0.4 (python)","vulnerabilityID":"GHSA-6vqw-3v5j-54x4"},"fix":{"suggestedVersion":"42.0.4"}}],"artifact":{"id":"8dca804f066e3dc8","name":"cryptography","version":"41.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"68.1.2"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"a606ddc92fb2947e","name":"setuptools","version":"68.1.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-68.1.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:68.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@68.1.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.3"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"8dca804f066e3dc8","name":"cryptography","version":"41.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-g4mx-q9vg-27p4","dataSource":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's request body not stripped after redirect from 303 status changes request method to GET","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}],"fix":{"versions":["1.26.18"],"state":"fixed"},"advisories":[],"risk":0.02852},"relatedVulnerabilities":[{"id":"CVE-2023-45803","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get","https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.16"}},"found":{"versionConstraint":">=0,<1.26.18 (python)","vulnerabilityID":"GHSA-g4mx-q9vg-27p4"},"fix":{"suggestedVersion":"1.26.18"}}],"artifact":{"id":"4c4a01f87de9f09d","name":"urllib3","version":"1.26.16","type":"python","locations":[{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.16:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.16","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfmj-5v4g-7637","dataSource":"https://github.com/advisories/GHSA-jfmj-5v4g-7637","namespace":"github:language:python","severity":"Medium","urls":[],"description":"zipp Denial of Service vulnerability","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5569","epss":0.00042,"percentile":0.12193,"date":"2025-06-03"}],"fix":{"versions":["3.19.1"],"state":"fixed"},"advisories":[],"risk":0.023520000000000003},"relatedVulnerabilities":[{"id":"CVE-2024-5569","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-5569","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd","https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae","https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd","https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae"],"description":"A Denial of Service (DoS) vulnerability exists in the jaraco/zipp library, affecting all versions prior to 3.19.1. The vulnerability is triggered when processing a specially crafted zip file that leads to an infinite loop. This issue also impacts the zipfile module of CPython, as features from the third-party zipp library are later merged into CPython, and the affected code is identical in both projects. The infinite loop can be initiated through the use of functions affecting the `Path` module in both zipp and zipfile, such as `joinpath`, the overloaded division operator, and `iterdir`. Although the infinite loop is not resource exhaustive, it prevents the application from responding. The vulnerability was addressed in version 3.19.1 of jaraco/zipp.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5569","epss":0.00042,"percentile":0.12193,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"zipp","version":"3.16.2"}},"found":{"versionConstraint":"<3.19.1 (python)","vulnerabilityID":"GHSA-jfmj-5v4g-7637"},"fix":{"suggestedVersion":"3.19.1"}}],"artifact":{"id":"c6805d000dc0aa12","name":"zipp","version":"3.16.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/zipp-3.16.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/zipp-3.16.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/zipp-3.16.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/zipp-3.16.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/zipp-3.16.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/zipp-3.16.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:jason_r__coombs_project:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs_project:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs_project:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:zipp:python-zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:zipp:python_zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:python:zipp:3.16.2:*:*:*:*:*:*:*","cpe:2.3:a:zipp:zipp:3.16.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/zipp@3.16.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"23.2.1"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"f0522f48dde9cd67","name":"pip","version":"23.2.1","type":"python","locations":[{"path":"/lib/python3.10/site-packages/pip-23.2.1.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/pip-23.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/pip-23.2.1.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/pip-23.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/pip-23.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/pip-23.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:23.2.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:23.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@23.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}],"fix":{"versions":["1.26.19"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.16"}},"found":{"versionConstraint":"<1.26.19 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"1.26.19"}}],"artifact":{"id":"4c4a01f87de9f09d","name":"urllib3","version":"1.26.16","type":"python","locations":[{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/urllib3-1.26.16.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.16:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.16","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.31.0"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"afcad5df128267c6","name":"requests","version":"2.31.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/requests-2.31.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/requests-2.31.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/requests-2.31.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/requests-2.31.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/requests-2.31.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/requests-2.31.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.31.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.31.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-h4gh-qq45-vh27","dataSource":"https://github.com/advisories/GHSA-h4gh-qq45-vh27","namespace":"github:language:python","severity":"Medium","urls":[],"description":"pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["43.0.1"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.3"}},"found":{"versionConstraint":">=37.0.0,<43.0.1 (python)","vulnerabilityID":"GHSA-h4gh-qq45-vh27"},"fix":{"suggestedVersion":"43.0.1"}}],"artifact":{"id":"8dca804f066e3dc8","name":"cryptography","version":"41.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-v8gr-m533-ghj9","dataSource":"https://github.com/advisories/GHSA-v8gr-m533-ghj9","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.4"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.3"}},"found":{"versionConstraint":">=2.5,<41.0.4 (python)","vulnerabilityID":"GHSA-v8gr-m533-ghj9"},"fix":{"suggestedVersion":"41.0.4"}}],"artifact":{"id":"8dca804f066e3dc8","name":"cryptography","version":"41.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.3","upstreams":[]}}],"source":{"type":"sbom-file","target":"gam-bp-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/gam-bp-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/gam-bp-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:20:43.625922+01:00"}}
